### ISSUE TITLE
libpng fails to build on ARMv8

### ISSUE THREAD

**Issue by rmtheis** [rmtheis/tess-two#102]
./obj/local/arm64-v8a/objs/png/pngrutil.o: In function `png_init_filter_functions':
    /home/theis/ocr/tess/tess-two/jni/libpng/pngrutil.c:3942: undefined reference to `png_init_filter_functions_neon'

**Comment by steverichey** [comment]
Updating to `libpng` 1.7.0 seems to fix this.

**Comment by longnguyencmg** [comment]
Can you please help to check this error?

java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.halosolutions..../base.apk"],nativeLibraryDirectories=[/data/app/com.halosolutions..../lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "liblept.so"

**Comment by steverichey** [comment]
Messing with `libpng/Android.mk` to ensure that the `libpng/arm` files are built before the `common_SRC_FILES` are built seems to do the trick; on a recent attempt, I was unable to use `libpng` 1.7 to fix the issue.
