### ISSUE TITLE
LibPNG Error

### ISSUE THREAD

**Issue by droidandrew** [rmtheis/tess-two#107]
I'm can't  build tess-two for arm64-v8a

[arm64-v8a] SharedLibrary  : libpngt.so
./obj/local/arm64-v8a/objs/pngt/pngrutil.o: In function `png_init_filter_functions':
/media/collos/D23A4E413A4E22B9/Work/Android/Adoriasoft/scanner/src/android/tess/tess-two/jni/libpng/pngrutil.c:3942: undefined reference to `png_init_filter_functions_neon'
collect2: error: ld returned 1 exit status
make: *** [obj/local/arm64-v8a/libpngt.so] Error 1

I'm found this: http://sourceforge.net/p/libpng/bugs/230/

**Comment by rmtheis** [comment]
Nice find. Closing to merge with #102.
