### ISSUE TITLE
Support for more CPU and instruction sets?

### ISSUE THREAD

**Issue by DaRolla** [rmtheis/tess-two#108]
Hi there,

After building with ndk-build I get three folders: armeabi-v7a, mips and x86.

Using the newest Android Studio 1.4 Beta 4 and one simple NDK example I get the following folders: arm64-v8a, armeabi, armeabi-v7a, mips, mips64, x86 and x86_64.

So tess-two supports less ABIs (https://developer.android.com/ndk/guides/abis.html)

Thanks for this project and all the support,
DaRolla

**Comment by rmtheis** [comment]
You can build for other ABIs by uncommenting them in Application.mk:
https://github.com/rmtheis/tess-two/blob/master/tess-two/jni/Application.mk#L2
