### ISSUE TITLE
Support for more than one .traineddata?

### ISSUE THREAD

**Issue by DaRolla** [rmtheis/tess-two#109]
Hi there,
using Tesseract from the command line it is possible to use more than one .traineddata.

For example this one uses custom.traineddata and deu.traineddata:

tesseract my.jpg output -l custom+deu.

Can I use this mechanism within tess-two?

Greetings,
DaRolla

**Comment by rmtheis** [comment]
Yes--you can, by using a plus between the language codes passed to init().
