### ISSUE TITLE
Test cases usage & tutorial on Leptonica Java usage

### ISSUE THREAD

**Issue by yiakwy** [rmtheis/tess-two#110]
Hi, 

Could any body tell me how to see test results and guide me in using Leptonic for image processing in Android?

**Comment by rmtheis** [comment]
For seeing test results try the `runtests.sh` script.

**Comment by yiakwy** [comment]
Hi, thanks for your replying. However, if you use runtest.sh, I supporse
that you are using ocr engine itself. I have already wrote my own sh tool
with preprocessing wroting in Python openCV. But my question is that I want
to test the Java wrapper. I found that some of the functionality is
different from ocr engine itself, and I am curious intereted in how could I
use api provided by Java to do ocr job.

2015-09-21 10:25 GMT-04:00 Robert Theis <notifications@github.com>:
