### ISSUE TITLE
Not able to read digit like digital watch.

### ISSUE THREAD

**Issue by joginder89** [rmtheis/tess-two#111]
I am using data file for English. It is able to detect normal digit but it does not detect the digit like Digital watch. I have an image of digital watch and I want to read the digit of that digital watch. Is there any way or .traineddata file to detect these digit.  How can I create .traineddata file for this requirement ?

**Comment by rmtheis** [comment]
This isn't a bug, and it looks like you've already asked this elsewhere so I'm going to close this issue here.

**Comment by rmtheis** [comment]
http://stackoverflow.com/questions/17672705/text-detection-on-seven-segment-display-via-tesseract-ocr
