### ISSUE TITLE
Different results: Android vs Cygwin

### ISSUE THREAD

**Issue by DaRolla** [rmtheis/tess-two#112]
Hi there,

this project works with Tesseract v3.04.00 and Leptonica v1.72. Calling

    tesseract --version

on Cygwin64 I get the same versions:

    tesseract 3.04.00
      leptonica-1.72
        libgif 4.1.6(?) : libjpeg 8d (libjpeg-turbo 1.3.1) : libpng 1.6.17 : libtiff 4.0.3 : zlib 1.2.8 : libwebp 0.4.3

So I thought that using the same .traineddata files and the same Jpeg would lead to the same result.

Here comes the result on Android using tess-two (and PageSegMode set to PageSegMode.PSM_AUTO which is default as described here: http://tesseract-ocr.googlecode.com/git/doc/tesseract.1.html)
 
    Krankenkasse bzw. Kostenträger
    
    Name, Vorname des Versicherten
    
    Kassen-Nr. Versicherten-Nr.
    
    Betriebsstätten—Nr.
    
    [] Erstbescheinigung [] Folgebescheinigung
    Arbeitsunfall, Arbeitsunfall— dem Durchgangsarzt
    folgen, Berufskrankheit zugewiesen
    
    arbeitsunfähig seit | ’ l l | | |
    voraussichtlich arbeitsunfähig ' I l l I l '
    bis einschließlich
    
    festgestellt am | ' | ’ | ' |
    
    Bei verspäteter Vorlage draht Krankengeldverlust!
    
    Diagnose
     
Using Cygwin64 the following way:

    tesseract arbeitsunfaehigkeit.hausarzt.exp0.jpg with_training -l arbeitsunfaehigkeit+deu -psm 3

the result is:

    Bei verspäteter Vorlage droht Krankengeldverlust!
    
     
    
    Krankenkasse bzw. Kostenträger
    Name, Vorname des Versicherten
    geb. am
    Kassen-Nr. Versicherten—Nr. Status
    Betriebsstätten—Nr. Arzt—Nr. Datum
    Ü Erstbescheinigung [] Folgebescheinigung
    Arbeitsunfall, Arbeitsunfall— dem Durchgangsarzt
    folgen, Berufskrankheit zugewiesen
    arbeitsunfähig seit ' I | | | |
    voraussichtlich arbeitsunfähig | | | i | |
    bis einschließlich
    festgestellt am | | | | | [

Shouldn't both results be equal as they use the same library versions and the same page segment modes? 

Thanks for this project,
DaRolla

**Comment by DaRolla** [comment]
Here the Android Activity I use (especially to ensure that I do not reduce the bitmap's quality):

    public class MainActivity extends Activity {
    
        public static final String TAG = "Tesser-wer";
    
        @Override
        protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            setContentView(R.layout.activity_main);
    
            final Button button = (Button) findViewById(R.id.button);
            button.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    opticalCharacterRecognition();
                }
            });
        }
    
        protected void opticalCharacterRecognition() {
            final String path = Environment.getExternalStorageDirectory() + "/tesseract-ocr";
            final Bitmap bitmap = BitmapFactory.decodeFile(path + "/arbeitsunfaehigkeit.hausarzt.exp0.jpg");
    
            final TessBaseAPI tessBaseAPI = new TessBaseAPI();
            tessBaseAPI.setDebug(true);
    
            // https://github.com/rmtheis/tess-two/issues/109
            tessBaseAPI.init(path, "arbeitsunfaehigkeit+deu");
    
            // PSM_SINGLE_BLOCK is default in tess-two
            // PSM_AUTO is default in Tesseract (http://tesseract-ocr.googlecode.com/git/doc/tesseract.1.html)
            tessBaseAPI.setPageSegMode(TessBaseAPI.PageSegMode.PSM_AUTO);
        
            tessBaseAPI.setImage(bitmap);
            final String ocr = tessBaseAPI.getUTF8Text();
            tessBaseAPI.end();
    
            Log.v(TAG, ocr);
            dump(ocr);
    
            final EditText editText = (EditText) findViewById(R.id.editText1);
            editText.setText(ocr);
        }
    
        public void dump(final String content) {
            try {
                final String path = Environment.getExternalStorageDirectory() + "/tesseract-ocr";
                final File file = new File(path + "/ocr.txt");
                Log.v(TAG, file.toString());
                final FileWriter writer = new FileWriter(file);
                writer.append(content);
                writer.flush();
                writer.close();
                Log.v(TAG, "text dumped into file ocr.txt");
    
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.FROYO) {
                    MediaScannerConnection.scanFile(MainActivity.this, new String[] {
                            file.toString()
                    }, null, null);
                }
    
            } catch (IOException e) {
                Log.w(TAG,
                        "text NOT dumped into file ocr.txt. Please make sure that the android.permission.WRITE_EXTERNAL_STORAGE is enabled in the AndroidManifest.xml");
            }
        }
    
    }

**Comment by rmtheis** [comment]
It would be helpful if you would try to find out what the root cause of the discrepancy is, and make your test case reproducible by others. Try re-running the test without the third-party traineddata, using a tiff format image to avoid issues arising from the jpeg compression artifacts, and including a link to the image here.

**Comment by DaRolla** [comment]
Okay.

After installing Cygwin64 with the package "Tesseract" (including the language "deu" for German) you can do the following thing on the command line:

    tesseract SwgKi00.jpg result_cmd -l deu

The image SwgKi00.jpg can be found here: http://i.imgur.com/SwgKi00.jpg

In order to run that on Android you need the deu.traineddata (13.054 KB) from the folder cygwin64\usr\share\tessdata.

Just take your Android smartphone, create a folder named **terreract-ocr** on the SD card and copy **SwgKi00.jpg** there, create a subfolder **tessdata** and copy **deu.traineddata** there.

    - Android_smartphone
      + tesseract-ocr
        - SwgKi00.jpg
        + tessdata
          - deu.traineddata

Here comes the Activity:

    import android.app.Activity;
    import android.graphics.Bitmap;
    import android.graphics.BitmapFactory;
    import android.media.MediaScannerConnection;
    import android.os.Build;
    import android.os.Bundle;
    import android.os.Environment;
    import android.util.Log;
    import android.view.View;
    import android.widget.Button;
    import android.widget.EditText;

    import com.googlecode.tesseract.android.TessBaseAPI;

    import java.io.File;
    import java.io.FileWriter;
    import java.io.IOException;

    public class MainActivity extends Activity {

        public static final String TAG = "Tesser-wer";

        @Override
        protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            setContentView(R.layout.activity_main);

            final Button button = (Button) findViewById(R.id.button);
            button.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    opticalCharacterRecognition();
                }
            });
        }

        protected void opticalCharacterRecognition() {
            final String path = Environment.getExternalStorageDirectory() + "/tesseract-ocr";
            final Bitmap bitmap = BitmapFactory.decodeFile(path + "/SwgKi00.jpg");

            final TessBaseAPI tessBaseAPI = new TessBaseAPI();
            tessBaseAPI.setDebug(true);

            // https://github.com/rmtheis/tess-two/issues/109
            tessBaseAPI.init(path, "deu");

            // PSM_SINGLE_BLOCK is default in tess-two
            // PSM_AUTO is default in Tesseract (http://tesseract-ocr.googlecode.com/git/doc/tesseract.1.html)
            tessBaseAPI.setPageSegMode(TessBaseAPI.PageSegMode.PSM_AUTO);

            tessBaseAPI.setImage(bitmap);
            final String ocr = tessBaseAPI.getUTF8Text();
            tessBaseAPI.end();

            Log.v(TAG, ocr);
            dump(ocr);

            final EditText editText = (EditText) findViewById(R.id.editText1);
            editText.setText(ocr);
        }

        public void dump(final String content) {
            try {
                final String path = Environment.getExternalStorageDirectory() + "/tesseract-ocr";
                final File file = new File(path + "ocr.txt");
                final FileWriter writer = new FileWriter(file);
                writer.append(content);
                writer.flush();
                writer.close();
                Log.v(TAG, "text dumped into file ocr.txt");

                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.FROYO) {
                    MediaScannerConnection.scanFile(MainActivity.this, new String[] {
                            file.toString()
                    }, null, null);
                }

            } catch (IOException e) {
                Log.w(TAG,
                        "text NOT dumped into file ocr.txt. Please make sure that the android.permission.WRITE_EXTERNAL_STORAGE is enabled in the AndroidManifest.xml");
            }
        }
    }

**Comment by DaRolla** [comment]
Ok, I added the project to GitHub:

https://github.com/DaRolla/Tesser-wer

**Comment by DaRolla** [comment]
I converted the JPEG into PNG.

Here is the PNG:
https://drive.google.com/file/d/0B9pm-ZPE_lYVUzBmRWpfdXM2UHc/view?usp=sharing

Here is the dump from the Android app:
https://drive.google.com/file/d/0B9pm-ZPE_lYVQ2piOVVLQnBSbU0/view?usp=sharing

Here ist the output from Cygwin's Tesseract command line call:
https://drive.google.com/file/d/0B9pm-ZPE_lYVcmctbkJZdnNZbnc/view?usp=sharing

**Comment by rmtheis** [comment]
Please reopen if you can track this issue down to a specific problem with code in this project. As-is, this issue is too high-level to be useful as a bug report.
