### ISSUE TITLE
UnsatisfiedLinkError couldn't find "libpngt.so" 

### ISSUE THREAD

**Issue by achinverma** [rmtheis/tess-two#113]
hi
i am using this library but when import this library and i run in eclipse i got error
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/edu.sfsu.cs.orange.ocr-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libpngt.so"
09-25 16:32:04.866: E/AndroidRuntime(30754): 	at java.lang.Runtime.loadLibrary(Runtime.java:366)
09-25 16:32:04.866: E/AndroidRuntime(30754): 	at java.lang.System.loadLibrary(System.java:988)
09-25 16:32:04.866: E/AndroidRuntime(30754): 	at com.googlecode.tesseract.android.TessBaseAPI.<clinit>(TessBaseAPI.java:43)
09-25 16:32:04.866: E/AndroidRuntime(30754): 	at edu.sfsu.cs.orange.ocr.CaptureActivity.initOcrEngine(CaptureActivity.java:711)
09-25 16:32:04.866: E/AndroidRuntime(30754): 	at edu.sfsu.cs.orange.ocr.CaptureActivity.onResume(CaptureActivity.java:368)
09-25 16:32:04.866: E/AndroidRuntime(30754): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1257)

**Comment by rmtheis** [comment]
Please reopen with more details. Did you follow the build instructions, and did you get `BUILD SUCCESSFUL`?

**Comment by achinverma** [comment]
i am using eclipse , i have followed the build instructions but after importing when i run this sample i got the above error,i will post my workspace screen shot.
![untitled2](https://cloud.githubusercontent.com/assets/2811593/10115727/fcde454a-6430-11e5-8f38-e6dcebd94a20.png)

![untitled](https://cloud.githubusercontent.com/assets/2811593/10115725/f28793e4-6430-11e5-9daf-ba07a58a1750.png)

**Comment by rmtheis** [comment]
The libs folder is missing from your tess-two project. To fix it, re-run the steps in the build instructions, be sure you get `BUILD SUCCESSFUL`, and do a fresh import of the project into Eclipse.

**Comment by achinverma** [comment]
hi @rmtheis  , thanks for your reply, i got your point and now i understand the cause of error,
but i don't know about ndk , so can you please mail me  tess-two project if you have in your pc, my mail id is 
achinverma1990@gmail.com

**Comment by achinverma** [comment]
hi i have downloaded the libs folder from here https://github.com/hareeshganesan/tesseractstuff/tree/master/tesseract-android-tools/libs

and now i am getting below error
java.lang.NoSuchFieldError: no "I" field "mNativeData" in class "Lcom/googlecode/tesseract/android/TessBaseAPI;" or its superclasses
09-28 11:43:47.579: E/AndroidRuntime(31034): 	at com.googlecode.tesseract.android.TessBaseAPI.nativeClassInit(Native Method)
09-28 11:43:47.579: E/AndroidRuntime(31034): 	at com.googlecode.tesseract.android.TessBaseAPI.<clinit>(TessBaseAPI.java:47)
09-28 11:43:47.579: E/AndroidRuntime(31034): 	at edu.sfsu.cs.orange.ocr.CaptureActivity.initOcrEngine(CaptureActivity.java:712)
09-28 11:43:47.579: E/AndroidRuntime(31034): 	at edu.sfsu.cs.orange.ocr.CaptureActivity.onResume(CaptureActivity.java:369)
09-28 11:43:47.579: E/AndroidRuntime(31034): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1257)
 
![untitled](https://cloud.githubusercontent.com/assets/2811593/10128961/95877932-65d6-11e5-98a2-dea464ce3ae4.png)

**Comment by vivekmishra0511** [comment]
do not update any gradle aur sdk update... i repeat ..do ignore all the update if asking and it will work smoothly.
