### ISSUE TITLE
No implementation found for boolean TessBaseAPI.nativeInitOem

### ISSUE THREAD

**Issue by achinverma** [rmtheis/tess-two#114]
hi i have downloaded the libs folder from here   https://github.com/hareeshganesan/tesseractstuff/tree/master/tesseract-android-tools/libs

i don't know about ndk, that's why i downloaded the libs from above link or if you think this error is due to my libs then  can you please mail me tess-two project with the missing libs folder, if you have in your pc, my mail id is 
achinverma1990@gmail.com 
and now i am getting below error
No implementation found for boolean com.googlecode.tesseract.android.TessBaseAPI.nativeInitOem(java.lang.String, java.lang.String, int) (tried Java_com_googlecode_tesseract_android_TessBaseAPI_nativeInitOem and Java_com_googlecode_tesseract_android_TessBaseAPI_nativeInitOem__Ljava_lang_String_2Ljava_lang_String_2I)

09-28 16:13:48.109: E/AndroidRuntime(13435): java.lang.RuntimeException: An error occured while executing doInBackground()
09-28 16:13:48.109: E/AndroidRuntime(13435): at android.os.AsyncTask$3.done(AsyncTask.java:304)
09-28 16:13:48.109: E/AndroidRuntime(13435): at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
09-28 16:13:48.109: E/AndroidRuntime(13435): at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
09-28 16:13:48.109: E/AndroidRuntime(13435): at java.util.concurrent.FutureTask.run(FutureTask.java:242)
09-28 16:13:48.109: E/AndroidRuntime(13435): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
09-28 16:13:48.109: E/AndroidRuntime(13435): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
09-28 16:13:48.109: E/AndroidRuntime(13435): at java.lang.Thread.run(Thread.java:818)
09-28 16:13:48.109: E/AndroidRuntime(13435): Caused by: java.lang.UnsatisfiedLinkError: No implementation found for boolean com.googlecode.tesseract.android.TessBaseAPI.nativeInitOem(java.lang.String, java.lang.String, int) (tried Java_com_googlecode_tesseract_android_TessBaseAPI_nativeInitOem and Java_com_googlecode_tesseract_android_TessBaseAPI_nativeInitOem__Ljava_lang_String_2Ljava_lang_String_2I)
09-28 16:13:48.109: E/AndroidRuntime(13435): at com.googlecode.tesseract.android.TessBaseAPI.nativeInitOem(Native Method)
09-28 16:13:48.109: E/AndroidRuntime(13435): at com.googlecode.tesseract.android.TessBaseAPI.init(TessBaseAPI.java:357)
09-28 16:13:48.109: E/AndroidRuntime(13435): at edu.sfsu.cs.orange.ocr.OcrInitAsyncTask.doInBackground(OcrInitAsyncTask.java:297)
09-28 16:13:48.109: E/AndroidRuntime(13435): at edu.sfsu.cs.orange.ocr.OcrInitAsyncTask.doInBackground(OcrInitAsyncTask.java:1)
09-28 16:13:48.109: E/AndroidRuntime(13435): at android.os.AsyncTask$2.call(AsyncTask.java:292)
09-28 16:13:48.109: E/AndroidRuntime(13435): at java.util.concurrent.FutureTask.run(FutureTask.java:237)

https://cloud.githubusercontent.com/assets/2811593/10128961/95877932-65d6-11e5-98a2-dea464ce3ae4.png

**Comment by rmtheis** [comment]
The pre-built libraries you found on another project won't work because they were built from a different version of the code.

**Comment by Swethamr402** [comment]
HI can you please share the links in which version it works fine.

**Comment by rmtheis** [comment]
@Swethamr402 That's a question for the publisher of that project. I don't know which version he built the libraries from.
