### ISSUE TITLE
GetUTF8Text() monitor and multi-platform projects

### ISSUE THREAD

**Issue by Jaykob** [rmtheis/tess-two#116]
We're working on a multi-platform project (iOS, Android, OS X) and use your project to compile tesseract for Android.
What strikes us is that you made changes to baseapi.h. Would it be possible to still provide the original tesseract API calls, e.g. GetUTF8Text() without a parameter? Adding new functions is fine, but removing the original ones makes life hard for cross-platform developers...

**Comment by rmtheis** [comment]
Thanks for the feedback. That's a good point.

If some incarnation of support for a monitor (tesseract-ocr/tesseract/#27) is merged into Tesseract, this project will be able to use Tesseract's baseApi class without the customizations.

Let's leave this issue open as a reminder that this is something that needs attention in the meantime.
