### ISSUE TITLE
[eyes-two]OutOfMemory Exception on Recognize activity

### ISSUE THREAD

**Issue by raimondz** [rmtheis/tess-two#118]
Hi, I tried to use Recognize activity on an Image with dimension 376X137 but it crashed on class OcrTaskProcessor.java in function processPix.(Line 523 Pixa pixa = unsorted.sort(Constants.L_SORT_BY_Y, Constants.L_SORT_INCREASING);)

**Comment by rmtheis** [comment]
I'm planning (#95) to remove the OcrTaskProcessor code from the eyes-two project. I'm not planning on fixing issues in that project so you'd need to implement a fix for this issue yourself.

In the meantime you may want to have a look at making an effort to customize the Google Vision API to do what you want. It's basically a nicer implementation of the eyes-two project, but it doesn't support text detection or OCR at this point.

**Comment by raimondz** [comment]
Ok, thanks
