### ISSUE TITLE
Use Relinker against unreliable Linking of Native Libs

### ISSUE THREAD

**Issue by Kadrei** [rmtheis/tess-two#127]
Maybe the Library could use [Relinker](https://github.com/KeepSafe/ReLinker).
I don't have any Experience with it, but I sometimes have Problems with the Internal Packaging of the .so-Files into the .apk. (A simple restart of Android Studio & Clean Project fixes it, but it is still painful, but doesn't seem to be a fault in my project) 
This might fix my issue.

**Comment by rmtheis** [comment]
Right now I'm not seeing occurrences in the wild of the UnsatisfiedLinkError that Relinker aims to fix, and if they do come up, I'd want to try to fix or work around the individual underlying issues first.

I don't think that Relinker will fix the packaging problem that you see sometimes on Android Studio, which sounds more like a problem on the tools side.

In the meantime, there's nothing preventing from users of this library from using Relinker on their own and I'd be interested in hearing about people's experiences with it.
