### ISSUE TITLE
can't resolve symbol 'IOcr' in  OCR.java  

### ISSUE THREAD

**Issue by lytasky** [rmtheis/tess-two#128]
in library eyes-two  :  can't resolve symbol 'IOcr' in  OCR.java

**Comment by Kadrei** [comment]
that might be related to your project structure. When you use Android Studio then IOCr wont be recognized by AS afair, because IOCr is an .aidl-File.

Adding something like
```
aidl.srcDirs = ['src']
```
to your build.gradle should fix that

**Comment by lytasky** [comment]
thank you
