### ISSUE TITLE
percentage progress values begin 30% instead of 0%

### ISSUE THREAD

**Issue by greenwind1202** [rmtheis/tess-two#130]
Hi all,
I tried to write some code for display progress values during OCR on a progress bar. But it always start with 30% instead of 0%. Here is my code:
TessBaseAPI baseApi = new TessBaseAPI(new TessBaseAPI.ProgressNotifier() {
                                @Override
                                public void onProgressValues(TessBaseAPI.ProgressValues progressValues) {
                                    Log.i(TAG,String.valueOf(progressValues.getPercent()));
                                    progressDialog.setProgress(progressValues.getPercent());
                                }
                            });
baseApi.init(EXSTORAGE_PATH, "eng");

Please help me to resolve this issue. Thanks.

**Comment by Kadrei** [comment]
Have the same Bug.

You might easily work around that Bug with:
```
double progress = progressValues.getPercent();
progress = (progress-30)/70;
```

**Comment by greenwind1202** [comment]
Thanks for your solution @Kadrei

**Comment by renard314** [comment]
The root cause can be found in the tess sources.  Look for assignments in to monitor->progress in control.cpp and apply the fix there

**Comment by Fibinacci** [comment]
@greenwind1202 I use like this but always progressValues.getPercent() always get 0 values.
Everything work but i check log all values=0. What could cause this ?
