### ISSUE TITLE
user_patterns

### ISSUE THREAD

**Issue by AmirAliSobhGol** [rmtheis/tess-two#134]
Hi,
i'm using tess-two to recognize passport mrz.
so i set the page segmentation to PSM_SINGLE_WORD
i set the whitelist to A-Z 0-9 <
now i want to give tesseract the pattern of mrz (first char is alpha, 2-49 is alpha+< etc)
i read issue[ #45](https://github.com/rmtheis/tess-two/issues/45) but i didn't quite get what should i do.
i would appreciate it if someone would tell me how to do so?

**Comment by rmtheis** [comment]
`user_patterns_suffix` is not available. See #64.
