### ISSUE TITLE
NDK r11 clang build error: undefined reference to isnanf/__isinff

### ISSUE THREAD

**Issue by rmtheis** [rmtheis/tess-two#138]
```
[armeabi] SharedLibrary  : libtess.so
jni/com_googlecode_tesseract_android/src/classify/featdefs.cpp:228: error: undefined reference to 'isnanf'
jni/com_googlecode_tesseract_android/src/classify/featdefs.cpp:228: error: undefined reference to '__isinff'
jni/com_googlecode_tesseract_android/src/classify/mf.cpp:75: error: undefined reference to 'isnanf'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [obj/local/armeabi/libtess.so] Error 1
```

**Comment by EfeVural** [comment]
hi ;
i have this error;i have to compile asap; if i use r10 may i walk around this bug?

**Comment by rmtheis** [comment]
I don't see this bug when I build with NDK r10e.

**Comment by JongImLee** [comment]
I tried to compile tess-two with both of NDK and only worked on using NDK r10e.
I think some are deprecated in r11.
If you use it asap, download and install r10e through this link(http://stackoverflow.com/questions/6849981/where-do-i-find-old-versions-of-android-ndk)

**Comment by EfeVural** [comment]
Hi again;
thank you very much ; with r10e i have built too.

**Comment by GiovanniCardamone** [comment]
I Confirm, i have the same problem with architecture x86
`[x86] Install        : libtess.so => libs/x86/libtess.so
jni/com_googlecode_tesseract_android/src/classify/featdefs.cpp:228: error: undefined reference to 'isnanf'
jni/com_googlecode_tesseract_android/src/classify/featdefs.cpp:228: error: undefined reference to '__isinff'
jni/com_googlecode_tesseract_android/src/classify/mf.cpp:75: error: undefined reference to 'isnanf'
collect2: error: ld returned 1 exit status
make: *** [obj/local/armeabi-v7a/libtess.so] Errore 1
make: *** Attesa per i processi non terminati....
jni/com_googlecode_tesseract_android/src/classify/featdefs.cpp:228: error: undefined reference to 'isnanf'
jni/com_googlecode_tesseract_android/src/classify/featdefs.cpp:228: error: undefined reference to '__isinff'
jni/com_googlecode_tesseract_android/src/classify/mf.cpp:75: error: undefined reference to 'isnanf'
collect2: error: ld returned 1 exit status
make: *** [obj/local/armeabi/libtess.so] Errore 1
`

only it works up to version r10e

**Comment by rmtheis** [comment]
http://stackoverflow.com/q/36056720/667810

**Comment by rmtheis** [comment]
https://github.com/android-ndk/ndk/issues/44
