### ISSUE TITLE
tess-two> ndk-build error ! [ cmd : Windows 7 64 bit ]

### ISSUE THREAD

**Issue by massodasuki** [rmtheis/tess-two#140]
Assembler message:
Error: can't open C:\Windows\TEMP\trainingsampleset-b8dd3f.s for reading: No such file file or directory
clang++.exe: error: assembler command failed with exit code 1 <use -v to see invocation>
make.exe: *** [obj/local/armebi/objs/tess/src/classify/trainingsampleset.o] Error 1

I am using ndk-r10e .. 

Any ideas, how to fix this ?

**Comment by rmtheis** [comment]
Try `ndk-build clean`.
