### ISSUE TITLE
Default datapath of tessdata

### ISSUE THREAD

**Issue by naga2raja** [rmtheis/tess-two#141]
Hi,

I found a strange issue like even If I explicitly mention the datapath to be /data/local/tmp/tesseract/, the TessBaseAPI uses the tessdata inside /data/data/tesseract/ (Only if it exists). If tesseract directory does not exist inside /data/data folder then the given path is taken.

I almost searched the entire TessBaseAPI.java file, but I couldn't find the default path.

Following are the code sample:
String TESSBASE_PATH = "/data/local/tmp/tesseract/";
TessBaseAPI baseApi = new TessBaseAPI();
baseApi.init(TESSBASE_PATH, "eng");

Can you please let me know from where the default datapath is taken?

**Comment by rmtheis** [comment]
http://stackoverflow.com/questions/36005221/default-datapath-of-tessdata-folder
