### ISSUE TITLE
Error:Execution failed for task ':tess-two:ndkBuild'

### ISSUE THREAD

**Issue by MahmoudAlnouno** [rmtheis/tess-two#142]
Error:Execution failed for task ':tess-two:ndkBuild'. > A problem occurred starting process 'command 'null/ndk-build.cmd''

**Comment by rmtheis** [comment]
You didn't leave any details, but it looks like the NDK isn't installed on your machine. Try using the precompiled binary instead.

**Comment by MahmoudAlnouno** [comment]
I have ndk 
this error just when open this app in android studio

**Comment by Harin-Kaklotar** [comment]
@rmtheis i have android ndk version r11c, add environment variable and import your project in android studio but it give tess-two:ndkBuild FAILED error.
Please put some video tutorial for import and run this project 
thank you. :)

**Comment by rmtheis** [comment]
@MahmoudAlnouno @Harin-Kaklotar Please open a new issue with thorough details describing how to reproduce the problem.
