### ISSUE TITLE
Leptonica detect image orientation feature request 

### ISSUE THREAD

**Issue by kuoliangkwong** [rmtheis/tess-two#143]
Hi,

I checked from the source code and it seems like it does not have the native interface for Leptonica flipdetect.c for image orientation detection. Is it possible if we can add it in?

**Comment by kuoliangkwong** [comment]
Hi rmtheis,

We would like to know when is the target date for this enhancement. We're working on a project and we're still in pending for this feature. It'd be great if we know the timeline so we could plan ahead.

**Comment by rmtheis** [comment]
@kuoliangkwong I don't have plans to work on this enhancement.

**Comment by rmtheis** [comment]
Closing old issues that haven't been acted on.
