### ISSUE TITLE
Step to install

### ISSUE THREAD

**Issue by edvenkat** [rmtheis/tess-two#144]
I am using following url to install 

http://scn.sap.com/community/developer-center/front-end/blog/2015/05/15/create-an-ocr-android-app-with-cordova-and-tesseract

but i am getting error.

cannot delove the KNI finction in com.googlecode.tesseract.android;
all native function are error like nativeGetUTF8Text ,etc... 

Please advice........

**Comment by rmtheis** [comment]
I'm not familiar with Cordova/PhoneGap, but this seems to be a problem with your setup and not a problem with this project. Please reopen if you can narrow down the problem to something in this project.

**Comment by edvenkat** [comment]
tesseract ocr with android 
what we did
1. We have created the Cordova project.
2. We have added tess-two in to Cordova project by using https://github.com/rmtheis/tess-two
3. Updated the build.gradle (Android) dependency compile project(:libraries:tess-two) and updated the setting.gradle include ':libraries:tess-two'.
using this URL https://coderwall.com/p/eurvaq/tesseract-with-andoird-and-gradle
4. build successfully but getting error at line 
TessBaseAPI baseApi = new TessBaseAPI();
object creation.
"no jni_onload found in /data/app-lib/" .
 like this http://stackoverflow.com/questions/11798054/no-jni-onload-found-in-skipping-init

please advice.........

main refer url http://scn.sap.com/community/developer-center/front-end/blog/2015/05/15/create-an-ocr-android-app-with-cordova-and-tesseract

**Comment by rmtheis** [comment]
@edvenkat That doesn't really narrow down the issue to a problem in this project. Maybe try asking on Cordova forums somewhere or on StackOverflow.

**Comment by edvenkat** [comment]
Okay

**Comment by edvenkat** [comment]
"field_mNativeData = env->GetFieldID(clazz, "mNativeData", "J");"

java.lang.NoSuchFieldError: no field with name='mNativeData' signature='J' in class Lcom/googlecode/tesseract/android/TessBaseAPI;

**Comment by rmtheis** [comment]
@edvenkat Your Cordova project has either (1) old code copied from this project or (2) an old pre-built binary built from this project. This is not a problem with this project, it's a problem with the Cordova project you're using.
