### ISSUE TITLE
tess-two for arm 64

### ISSUE THREAD

**Issue by mustansarsaeed** [rmtheis/tess-two#146]
Hi,

liplept.so and liptess.so are for 32 bit architecture. What is the method for building tess-two for arm 64 bit architecture?

**Comment by edvenkat** [comment]
i think native-lib.....

**Comment by rmtheis** [comment]
@mustansarsaeed The default is to support all Android ABIs, you don't need to change anything. See: https://github.com/rmtheis/tess-two/blob/master/tess-two/jni/Application.mk#L2

**Comment by BraisGabin** [comment]
Hi, I was developing my app using tess-two and one of my test phones was a Nexus 6P (`arm64-v8a`). All warked perfectly. tess-two is quite heavy so I decided to split my APK for the different architectures. Now I can't install the `arm64-v8a` version in my Nexus 6P. The `armeabi-v7a` works perfectly on it.

Is this a tess-two problem or there is something wrong in my configuration? The project is Open Source and here is the build.gradle https://github.com/BraisGabin/pokescreenshot/blob/master/app/build.gradle#L23-L30

**Comment by rmtheis** [comment]
@BraisGabin Would you please open your issue as a new issue, and leave more more detail about what's wrong? For example, what do you mean by "I can't install the `arm64-v8a` version" -- what's preventing it? Are you seeing an error, or what?

**Comment by BraisGabin** [comment]
Sorry, you are completely right. My report was terrible. I think that I spot with an Android error. I had tess-two as a dependency in a module that I add to my project. If I add the dependency to my main project all works perfectly.
