### ISSUE TITLE
NoClassDefFoundError - TessBaseAPI

### ISSUE THREAD

**Issue by tomday** [rmtheis/tess-two#149]
I have imported the Tesseract API via the gradle compile command you provide in the README but I get this error:
```java
stack=java.lang.NoClassDefFoundError: Failed resolution of: Lcom/googlecode/tesseract/android/TessBaseAPI;
```
There are no errors in my code. This error only appears at runtime. I have included `import com.googlecode.tesseract.android.TessBaseAPI;` as suggested by Android Studio.

**Comment by tomday** [comment]
The issue resolved itself for some unknown reason.

**Comment by Sergioct** [comment]
Today i had the same problem. Clean the project and try it again.
