### ISSUE TITLE
Execution failed for task ':tess-two:ndkBuild'

### ISSUE THREAD

**Issue by aneeshATgithub** [rmtheis/tess-two#151]
I cannot compile the 'tess' project. I am using Android Studio 2.1.1 and on ubuntu (14.04) machine. The ndk version I am using is, android-ndk-r8b, and I also tried with android-ndk-r10b. 

The following message is getting,

Android NDK: NDK Application 'local' targets unknown ABI(s): arm64-v8a x86_64 mips64    
Android NDK: Please fix the APP_ABI definition in ./jni/Application.mk    

But, I have put     APP_ABI := armeabi armeabi-v7a x86 x86-64  in Makefile.am

**Comment by rmtheis** [comment]
@aneeshATgithub The default values [here](https://github.com/rmtheis/tess-two/blob/master/tess-two/jni/Application.mk#L2) are correct. It looks like you are using a dash instead of an underscore.

**Comment by aneeshATgithub** [comment]
ok, I changed to  APP_ABI := armeabi armeabi-v7a x86 mips arm64-v8a x86_64 mips64
in Application.mk file in tess-two 

But, I have the following Messages while building tess-two, and cannot build



Information:Gradle tasks [:tess-two-test:generateDebugSources, :tess-two-test:generateDebugAndroidTestSources, :tess-two-test:mockableAndroidJar, :tess-two-test:prepareDebugUnitTestDependencies, :tess-two:generateDebugSources, :tess-two:mockableAndroidJar, :tess-two:prepareDebugUnitTestDependencies, :tess-two:generateDebugAndroidTestSources, :eyes-two:generateDebugSources, :eyes-two:mockableAndroidJar, :eyes-two:prepareDebugUnitTestDependencies, :eyes-two:generateDebugAndroidTestSources]
:tess-two-test:preBuild UP-TO-DATE
:tess-two-test:preDebugBuild UP-TO-DATE
:tess-two-test:checkDebugManifest
:tess-two-test:preReleaseBuild UP-TO-DATE
:tess-two-test:generateDebugBuildConfig
:tess-two:preBuild UP-TO-DATE
:eyes-two:preBuild
:tess-two:preReleaseBuild UP-TO-DATE
:eyes-two:preBuild UP-TO-DATE
:tess-two:compileReleaseNdk
:eyes-two:preDebugBuild UP-TO-DATE
:eyes-two:checkDebugManifest
:eyes-two:preDebugAndroidTestBuild UP-TO-DATE
:eyes-two:preDebugUnitTestBuild UP-TO-DATE
:eyes-two:preReleaseBuild UP-TO-DATE
:eyes-two:preReleaseUnitTestBuild UP-TO-DATE
:eyes-two:generateDebugBuildConfig UP-TO-DATE
:eyes-two:mergeDebugShaders UP-TO-DATE
:tess-two-test:generateDebugBuildConfig UP-TO-DATE
:tess-two-test:mergeDebugShaders
:tess-two:compileReleaseNdk UP-TO-DATE
:tess-two:compileLint
:eyes-two:compileDebugShaders
:tess-two:copyReleaseLint UP-TO-DATE
:tess-two:mergeReleaseProguardFiles
:tess-two-test:mergeDebugShaders UP-TO-DATE
:tess-two-test:compileDebugShaders UP-TO-DATE
:tess-two-test:generateDebugAssets UP-TO-DATE
:tess-two-test:generateDebugResValues UP-TO-DATE
:tess-two-test:preDebugAndroidTestBuild UP-TO-DATE
:tess-two-test:prepareDebugAndroidTestDependencies
:tess-two-test:compileDebugAndroidTestAidl UP-TO-DATE
:eyes-two:compileDebugShaders UP-TO-DATE
:eyes-two:generateDebugAssets UP-TO-DATE
:eyes-two:generateDebugResValues UP-TO-DATE
:eyes-two:mockableAndroidJar UP-TO-DATE
:eyes-two:compileDebugNdk UP-TO-DATE
:tess-two:mergeReleaseProguardFiles UP-TO-DATE
:tess-two:packageReleaseRenderscript UP-TO-DATE
:tess-two:checkReleaseManifest
:tess-two:prepareReleaseDependencies
:tess-two:compileReleaseRenderscript
:eyes-two:compileLint
:eyes-two:copyDebugLint UP-TO-DATE
:eyes-two:mergeDebugProguardFiles UP-TO-DATE
:eyes-two:packageDebugRenderscript
:tess-two-test:processDebugAndroidTestManifest UP-TO-DATE
:tess-two-test:compileDebugAndroidTestRenderscript
:tess-two:compileReleaseRenderscript UP-TO-DATE
:tess-two:generateReleaseResValues
:eyes-two:packageDebugRenderscript UP-TO-DATE
:eyes-two:incrementalDebugJavaCompilationSafeguard
:tess-two:generateReleaseResValues UP-TO-DATE
:tess-two:generateReleaseResources UP-TO-DATE
:tess-two:packageReleaseResources UP-TO-DATE
:tess-two:compileReleaseAidl UP-TO-DATE
:tess-two:generateReleaseBuildConfig
:eyes-two:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:tess-two:generateReleaseBuildConfig UP-TO-DATE
:tess-two:mergeReleaseShaders
:eyes-two:ndkBuild
:tess-two:mergeReleaseShaders UP-TO-DATE
:tess-two:compileReleaseShaders UP-TO-DATE
:tess-two:generateReleaseAssets UP-TO-DATE
:tess-two:mergeReleaseAssets UP-TO-DATE
:tess-two:processReleaseManifest UP-TO-DATE
:tess-two:processReleaseResources
:tess-two-test:generateDebugAndroidTestBuildConfig
:tess-two:processReleaseResources UP-TO-DATE
:tess-two:generateReleaseSources UP-TO-DATE
:tess-two:incrementalReleaseJavaCompilationSafeguard UP-TO-DATE
:tess-two:ndkBuild
:tess-two-test:mergeDebugAndroidTestShaders
:tess-two-test:compileDebugAndroidTestShaders
:tess-two-test:generateDebugAndroidTestAssets
:tess-two-test:mergeDebugAndroidTestAssets
:tess-two-test:generateDebugAndroidTestResValues UP-TO-DATE
:tess-two-test:generateDebugAndroidTestResources
:tess-two-test:mergeDebugAndroidTestResources
Android NDK: NDK Application 'local' targets unknown ABI(s): arm64-v8a x86_64 mips64    
Android NDK: Please fix the APP_ABI definition in /home/phenomtec/Desktop/tess-two-master/tess-two/jni/Application.mk    
make: Entering directory `/home/phenomtec/Desktop/tess-two-master/tess-two/jni'
make: Leaving directory `/home/phenomtec/Desktop/tess-two-master/tess-two/jni'
:tess-two:ndkBuild FAILED
Android NDK: NDK Application 'local' targets unknown ABI(s): arm64-v8a x86_64 mips64    
Android NDK: Please fix the APP_ABI definition in ./jni/Application.mk    
make: Entering directory `/home/phenomtec/Desktop/tess-two-master/eyes-two/src/main'
make: Leaving directory `/home/phenomtec/Desktop/tess-two-master/eyes-two/src/main'
/opt/android-ndk-r9/build/core/setup-app.mk
Error:(91) *** Android NDK: Aborting    .  Stop.
Error:(91) *** Android NDK: Aborting    .  Stop.
:eyes-two:ndkBuild FAILED
FAILURE: Build completed with 2 failures.
1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':tess-two:ndkBuild'.
> Process 'command '/opt/android-ndk-r9/ndk-build'' finished with non-zero exit value 2
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================
2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':eyes-two:ndkBuild'.
> Process 'command '/opt/android-ndk-r9/ndk-build'' finished with non-zero exit value 2
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================
Information:BUILD FAILED
Information:Total time: 1.87 secs
Information:2 errors
Information:0 warnings
Information:See complete output in console

**Comment by rmtheis** [comment]
@aneeshATgithub Use NDK r12b instead of r9. Or use [as prebuilt library](https://github.com/rmtheis/tess-two#usage).

**Comment by aneeshATgithub** [comment]
thanks, I could build succesfully with r12b

**Comment by aneeshATgithub** [comment]
But now I am facing an unsatisfiedlink error,

Please see this,
https://github.com/rmtheis/tess-two/issues/169
