### ISSUE TITLE
ndk-build error Windows Command Prompt

### ISSUE THREAD

**Issue by chandakvishal** [rmtheis/tess-two#152]
I am unable to find the cause of this issue, can you please provide some insights.
I am following the steps mentioned in BUILDING.md:

    git clone git://github.com/rmtheis/tess-two tess
    cd tess
    git checkout tags/5.4.0
    cd tess-two
    ndk-build
    android update project --path .
    ant release

But at ndk-build step it fails.

[armeabi-v7a] "Compile        ": "lept <= adaptmap.c"
process_begin: CreateProcess(NULL, C:/Android/android-ndk-r11c/build//../toolchains/arm-linux-androideabi-4.8/prebuilt/windows-x86_64/bin/arm-linux-androideabi-gcc -MMD -MP -MF ./obj/local/armeabi-v7a/objs/lept/src/src/adaptmap.o.d -Ijni/com_googlecode_leptonica_android -Ijni/com_googlecode_leptonica_android/src/src -Ijni/libpng -IC:/Android/android-ndk-r11c/build//../sources/cxx-stl/gnu-libstdc++/4.9/include -IC:/Android/android-ndk-r11c/build//../sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -IC:/Android/android-ndk-r11c/build//../sources/cxx-stl/gnu-libstdc++/4.9/include/backward -Ijni/com_googlecode_leptonica_android -DANDROID -DHAVE_CONFIG_H -Wa,--noexecstack -Wformat -Werror=format-security -isystem C:/Android/android-ndk-r11c/build//../platforms/android-8/arch-arm/usr/include -c jni/com_googlecode_leptonica_android/src/src/adaptmap.c -o ./obj/local/armeabi-v7a/objs/lept/src/src/adaptmap.o, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [obj/local/armeabi-v7a/objs/lept/src/src/adaptmap.o] Error 2

**Comment by rmtheis** [comment]
Thanks for pointing this out. You need to use NDK r10e instead of r11.

**Comment by elecstudent** [comment]
Hi there, 
For same examle , I got following error,"
error: error opening './obj/local/armeabi/objs/jpgt/jaricom.o.d': No such file
      or directory
1 error generated.
make.exe: *** [obj/local/armeabi/objs/jpgt/jaricom.o] Error 1 "

I am not sure to solve this error, any help will be highly appreciated :)
