### ISSUE TITLE
TessBaseAPI.ProgressNotifier issue

### ISSUE THREAD

**Issue by iAlex97** [rmtheis/tess-two#153]
After changing from '5.4.1' to '6.0.+' the TessBaseAPI.ProgressNotifier no longer gives smooth feedback of the OCR process, it waits a few seconds then jumps to 100% after it finishes.

**Comment by rmtheis** [comment]
The tess-two code for this has not changed significantly, so the source of this change is most likely in the Tesseract code. I suggest asking on the Tesseract mailing list (along with a sample image), or tracking down the source of the discrepancy within the Tesseract code to try to identify where it's coming from.

Also, keep in mind that the progress monitor covers word recognition and does not monitor layout analysis.

**Comment by rmtheis** [comment]
Reopening as a reminder to take a look at this issue.

**Comment by rmtheis** [comment]
Working as intended. I verified that the word recognition progress values still look correct and are coming back with values other than 0 and 100. It seems likely that this issue is due to the consuming app not updating the UI on the correct thread.

**Comment by iAlex97** [comment]
On what platforms are you testing? I've tried on both armv7 and arm64-v8a and I'm not receiving any progress until the OCR is completely finished. The problem is not about my UI as I'm logging the progress and I'm not seeing any output.

**Comment by rmtheis** [comment]
I'm using armv7. What do you see when you log the values for the testProgressValues test case?

**Comment by iAlex97** [comment]
I have managed to build the tests using Android Studio and the testProgressValues outputted the values 0, 35, 70, 85 which seem fine, but the problem is that in my project I'm not building tess-two from sources, I'm just using the gradle dependency.

Tomorrow I'll try to use the locally compiled version and I'll report.

Thanks!

**Comment by iAlex97** [comment]
It's still not working even if I compiled it myself. As far as I can tell the native code does not call the function `protected void onProgressValues(final int percent, final int left,
            final int right, final int top, final int bottom,
            final int textLeft, final int textRight, final int textTop, final int textBottom) ` thus the progress is never dispatched

**Comment by rmtheis** [comment]
Are you using version 6.0.4?

**Comment by iAlex97** [comment]
Yes

**Comment by rmtheis** [comment]
Try running this project: https://github.com/rmtheis/issue-153-progressnotifier

What type of device are you using, and what version of Android are you running on?

**Comment by iAlex97** [comment]
I tried both on my OnePlus 2 (Android 6.0.1) and on an Samsung SM-G531F (Android 5.1.1)

**Comment by iAlex97** [comment]
Ok, so I am able to get progress using this project, but only when using the `getHOCRText(0)`method. In my project I'm using the `getUTF8Text()` which seems to not properly dispatch the progress.

**Comment by iAlex97** [comment]
Is there any hope of easily fixing this or this is the expected behavior? I could probably parse the output of the `getHOCRText(0)`, but I don't care that much about box sizes and stuff like that.

**Comment by rmtheis** [comment]
This is the expected behavior. You need to use `getHOCRText` in order to receive progress updates.
