### ISSUE TITLE
new TessBaseAPI() crash

### ISSUE THREAD

**Issue by fangaofeng** [rmtheis/tess-two#162]
when i build apk is ok，but run is is crash.
try {
			tessBaseApi = new TessBaseAPI();

		} catch (Exception e) {
			Log.e(TAG, e.getMessage());
			if (tessBaseApi == null) {
				Log.e(TAG, "TessBaseAPI is null. TessFactory not returning tess object.");
			}
		}
this is app build.gradle
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.3"

    defaultConfig {
        applicationId "com.datumdroid.android.ocr.simple"
        minSdkVersion 16
        targetSdkVersion 23
    }
    dexOptions {
        incremental true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile project(':tess-two')

}

tess-two  by import module  add to project.
.

if i use  compile 'com.rmtheis:tess-two:5.4.1'， it can work
if i use  compile 'com.rmtheis:tess-two:6.0.0' or 6.0.1 or 6.0.2 ， ，it crash。
Test device is samsun note 2.

**Comment by rmtheis** [comment]
@fangaofeng What's the message that's printed to Logcat when it crashes?

**Comment by rmtheis** [comment]
@fangaofeng Please reopen this issue with more info
