### ISSUE TITLE
Is possible to read the some specific rect area (Not all content from image)

### ISSUE THREAD

**Issue by edvenkat** [rmtheis/tess-two#164]
Hai rmtheis....
any option are available,.
In ios we have the following option

// Optional: Limit the character set Tesseract should not try to recognize from //tesseract.charBlacklist = @"OoZzBbSs";

// Optional: Limit the character set Tesseract should try to recognize from
//tesseract.charWhitelist = @"0123456789";

// Optional: Limit the area of the image Tesseract should recognize on to a rectangle
//tesseract.rect = CGRectMake(0, 0, 320, 320);

please advice.....

**Comment by rmtheis** [comment]
See [`setRectangle`](https://rmtheis.github.io/tess-two/javadoc/com/googlecode/tesseract/android/TessBaseAPI.html#setRectangle(int,%20int,%20int,%20int)) and [`setVariable`](https://rmtheis.github.io/tess-two/javadoc/com/googlecode/tesseract/android/TessBaseAPI.html#setVariable(java.lang.String,%20java.lang.String)).
