### ISSUE TITLE
android studio2.1.2 not build

### ISSUE THREAD

**Issue by sujiewen** [rmtheis/tess-two#168]
// Call external ndk-build(.cmd) script to build the native code
    task ndkBuild(type: Exec) {
//        def ndkBuildExt = Os.isFamily(Os.FAMILY_WINDOWS) ? ".cmd" : ""
//        commandLine "ndk-build${ndkBuildExt}", '-C', file('src/main').absolutePath,
//                '-j', Runtime.runtime.availableProcessors()
        if (Os.isFamily(Os.FAMILY_WINDOWS)) {
            commandLine "ndk-build.cmd", '-C', file('src/main').absolutePath, '-j', Runtime.runtime.availableProcessors()
        }
        else {
            commandLine "/Users/Sjw/Library/Android/sdk/ndk-bundle/ndk-build", '-C', file('src/main').absolutePath, '-j', Runtime.runtime.availableProcessors()
    }
    }

    tasks.withType(JavaCompile) {
        compileTask -> compileTask.dependsOn ndkBuild
    }

    // Cleanup task to remove previously generated binaries
    task ndkClean(type: Exec) {
        if (Os.isFamily(Os.FAMILY_WINDOWS)) {
            commandLine "ndk-build.cmd", '-C', file('src/main').absolutePath, 'clean'
        }
        else {
            commandLine "/Users/Sjw/Library/Android/sdk/ndk-bundle/ndk-build", '-C', file('src/main').absolutePath, 'clean'
        }
//        def ndkBuildExt = Os.isFamily(Os.FAMILY_WINDOWS) ? ".cmd" : ""
//        commandLine "ndk-build${ndkBuildExt}", '-C', file('src/main').absolutePath, 'clean'
    }

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tess-two:ndkClean'.
> A problem occurred starting process 'command 'ndk-build''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by rmtheis** [comment]
@sujiewen Did you set the path to your NDK installation in the Project Structure dialog (File->Project Structure)?

**Comment by sujiewen** [comment]
@rmtheis 
Already set，See screenshot！Command line can compile。
<img width="848" alt="2016-08-17 17 18 05" src="https://cloud.githubusercontent.com/assets/1973318/17731161/badf1628-649e-11e6-896d-7371c72767b4.png">

**Comment by rmtheis** [comment]
Be sure to add your NDK folder to your PATH. If that does not fix it, please open a new issue with the stack trace and the complete steps needed to reproduce this.

**Comment by rmtheis** [comment]
See also: http://stackoverflow.com/questions/33725630/why-is-android-studio-ignoring-my-bashrc-file-on-osx
