### ISSUE TITLE
tess-two (or Tesseract) crashing with large images

### ISSUE THREAD

**Issue by TheWall89** [rmtheis/tess-two#17]
Hi,

I'm using tess-two without problems since March/April. As you upgraded to Tesseract 3.02 I downloaded the new source code, but I get errors with large images (about 1000x1000px)

10-11 11:13:13.135: I/Tesseract(native)(15675): Initialized Tesseract API with language=eng
10-11 11:13:13.255: D/memalloc(15675): /dev/pmem: Mapped buffer base:0x5612c000 size:21106688 offset:20811776 fd:75
10-11 11:13:13.365: D/memalloc(15675): /dev/pmem: Mapped buffer base:0x5760e000 size:21401600 offset:21106688 fd:82
10-11 11:13:13.795: D/memalloc(15675): /dev/pmem: Unmapping buffer base:0x548fa000 size:20811776 offset:20639744
10-11 11:13:14.696: D/dalvikvm(15675): Trying to load lib /data/data/com.matpergo.androcr/lib/liblept.so 0x40da57f0
10-11 11:13:14.696: D/dalvikvm(15675): Shared lib '/data/data/com.matpergo.androcr/lib/liblept.so' already loaded in same CL 0x40da57f0
10-11 11:13:14.786: D/dalvikvm(15675): Trying to load lib /data/data/com.matpergo.androcr/lib/liblept.so 0x40da57f0
10-11 11:13:14.786: D/dalvikvm(15675): Shared lib '/data/data/com.matpergo.androcr/lib/liblept.so' already loaded in same CL 0x40da57f0
10-11 11:13:15.727: A/libc(15675): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1)

The previous version works flawlessy with the same images...

Thanks for your great work, bye.

**Comment by maneeshbhunwal** [comment]
Hi all,
I am also running in the same issue,
i took the latest from 
https://github.com/tesseract-ocr/tessdata/blob/master/eng.traineddata
but still the app is hung.
Can you please help
Thanks
