### ISSUE TITLE
3.03 based tess two crashed when initializing certain languages using latest trained data

### ISSUE THREAD

**Issue by iori57** [rmtheis/tess-two#173]
My app is still using the older tess two library ehich was based on tesseract 3.03. Last time it was downloading the 3.02 trained data from old google site but since that has been moved to github, seemsblike they are hosting only the latest trained data. 

I tried several languages such as english and it is able to run with success, however several languages such as arabic, japanese and chinese seems to crash upon calling tess two init. It didn't spit anything in the logs (maybe crashed on native code) so I am not sure why it crashed. 

The question is will upgrading the library to the latest solve the crash issue? Thanks!

**Comment by rmtheis** [comment]
The latest version of the library works with the trained data files currently published on the [tessdata](https://github.com/tesseract-ocr/tessdata) project. I'm not sure which versions of the trained data file will work with your app as-is.
