### ISSUE TITLE
language pack extension

### ISSUE THREAD

**Issue by jjhesk** [rmtheis/tess-two#178]
It looks promising. Still are there any quick tutorial for implementation of this library?
What are the list of languages that is currently supported now?

**Comment by rmtheis** [comment]
> any quick tutorial for implementation of this library?

Not really, no. There's an [example project](https://github.com/rmtheis/android-ocr), though.

> What are the list of languages that is currently supported now?

Several are [available](https://github.com/tesseract-ocr/tessdata) pre-trained, or you can train your own.
