### ISSUE TITLE
nativeGetUTF8Text() crash

### ISSUE THREAD

**Issue by magar501** [rmtheis/tess-two#181]
I use tesserate to recognitise chinese word, when use tessBaseAPI.getUTF8Text() in thread or asyctask, it will be crash, I need your help, thanks。

**Comment by rmtheis** [comment]
Are you sure the problem is in this project and not in your code? Please reopen this issue when you can narrow down the source of the problem, and include steps for reproducing the problem.

**Comment by magar501** [comment]
Thanks for your response.
try {
	tessBaseAPI.setImage(bitmap);
	tessBaseAPI.setRectangle(0, 0, width, height);
	tessBaseAPI.setPageSegMode(TessBaseAPI.PageSegMode.PSM_SINGLE_LINE);
	if (tessBaseAPI.meanConfidence() > 60) {
		result = tessBaseAPI.getUTF8Text();
	}
	} catch (Exception e) {
		LogTool.exception(TAG, e);
	}
I debug this code, step to "tessBaseAPI.getUTF8Text()", will be crash when i user it in thread or asyctask.
but not in main thread.

**Comment by rmtheis** [comment]
@magar501 Confidence values are available only _after_ `getUTF8Text` is used.
