### ISSUE TITLE
chinese language  init failed

### ISSUE THREAD

**Issue by maxiaoyi** [rmtheis/tess-two#184]
chinese language  init failed,at TessBaseAPI.init();

**Comment by rmtheis** [comment]
Please reopen this issue with the text of the error message that you received. Also, are you using the new training data from the tessdata repo? `chi_sim` or `chi_tra`?

**Comment by maxiaoyi** [comment]
I  have used the latest training data,It crashed on TessBaseAPI.init();

At boolean success = nativeInitOem(mNativeData, datapath, language, ocrEngineMode);


Both English and Korean have been used successfully except Chinese;
The parameters of the method are all normal

**Comment by rmtheis** [comment]
1. What's the text of the error message you receive?
2. Are you using the new training data from the tessdata repo?
3. Which version of tess-two are you using?

**Comment by maxiaoyi** [comment]
1. No error message,native method crashed
2. The training data from 'https://github.com/tesseract-ocr/tessdata/' 
3. com.rmtheis:tess-two:6.1.1
4. 0

**Comment by rmtheis** [comment]
2. Was that before or after the "Added LSTM models" commit? Does the earlier version work?

**Comment by rmtheis** [comment]
See #188.
