### ISSUE TITLE
Crash  when i want to reuse TessBaseAPI instance

### ISSUE THREAD

**Issue by privatez** [rmtheis/tess-two#195]
When i want to reuse TessBaseAPI instance the app will crash and thorw
'A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8edaa3e1 in tid 4127 (Thread-4997)'

Tess-two version used:

6.2.0

**Comment by rmtheis** [comment]
Thanks for the crash report. Let's track this on #197.
