### ISSUE TITLE
Failed to read bitmap

### ISSUE THREAD

**Issue by yxwandroid** [rmtheis/tess-two#199]
Summary:
How to deal with Failed to read bitmap
 
Steps to reproduce the issue:

 baseApi.init(TESSBASE_PATH, DEFAULT_LANGUAGE); 
 baseApi.setImage(bmp); 
Expected result:
 Caused by: java.lang.RuntimeException: Failed to read bitmap
Actual result:

Tess-two version:

6.2.0

Android version:

Phone/device model:

Phone/device architecture (armeabi, armeabi-v7a, x86, mips, arm64-v8a, x86_64, mips64):

**Comment by rmtheis** [comment]
Can't say without more information. The error message is coming from [here](https://github.com/rmtheis/tess-two/blob/db698d0e4a13af1cfef593a246e0398d1c7c1ccb/tess-two/src/com/googlecode/tesseract/android/TessBaseAPI.java#L520), meaning that it failed in the native code. Maybe the bitmap you're passing in is too big?

**Comment by rmtheis** [comment]
You should also get another message printed to the log such as [`Failed to read pix from bitmap`](https://github.com/rmtheis/tess-two/blob/c3e038b2a5252b91398eb8601fa79c15fbef81f7/tess-two/src/com/googlecode/leptonica/android/ReadFile.java#L182).

**Comment by yxwandroid** [comment]
I Found the reason   

Bitmap config must be ARGB_8888
