### ISSUE TITLE
app crash when using two languages

### ISSUE THREAD

**Issue by nouhahammami** [rmtheis/tess-two#201]
Summary:
thanks for this solution for Android, but i have an issue, is that i can't use two languages (ara+fra , ara+eng ....), the app crash frequently specially when i pass a big text for tesseract

Actual result:
crash with this error 

![image](https://cloud.githubusercontent.com/assets/12768576/25378047/1ab1cb46-29a1-11e7-9098-a36aeda4c1a8.png)
![image](https://cloud.githubusercontent.com/assets/12768576/25378012/027ef0a8-29a1-11e7-9e74-8401ff46aa2a.png)

PS : numa it's my traindata for digit numbers, i got the same problem when i used ara+fra or fra+eng
Tess-two version: 6.3.0

Android version: 5.1

Phone/device model: huawei, samsung

Phone/device architecture : armeabi, armeabi-v7a

**Comment by rmtheis** [comment]
Arabic requires using Cube or combined modes.

Otherwise the problem is likely to be with your custom training data. Please open a new issue if this problem is reproducible with the regular training data.

**Comment by nouhahammami** [comment]
@rmtheis but it's the same problem when i use ara+fra or ara+eng

**Comment by rmtheis** [comment]
Please see my comment above about Arabic (`ara`) and open a new issue if necessary with a description of a single problem and all the minimal steps necessary to exactly reproduce the issue.

**Comment by nouhahammami** [comment]
okay thanks for your reply
