### ISSUE TITLE
Need modify quality image before OCR process ?

### ISSUE THREAD

**Issue by michaelDnguyen** [rmtheis/tess-two#210]
How to make image to ocr best quality ? Do I need to do image editing before? Examples: grayscale, black white, threshold process... 

Thanks & best regards,

**Comment by rmtheis** [comment]
This is an important question to the correctness of the resulting OCR. In general, yes, editing is needed. It depends on the details of what you're trying to recognize, so you'll have to research this based on your needs and see what works best.
