### ISSUE TITLE
 Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc in tid 514

### ISSUE THREAD

**Issue by wangyangke** [rmtheis/tess-two#219]
I in the project with Tess - two, but encountered this problem Fatal signal 11 (SIGSEGV), code 1, fault addr 0 xc dar in 514

**Comment by rmtheis** [comment]
Not enough info. Likely duplicate of #197.

**Comment by wangyangke** [comment]
Before android sdk5.0 is right, and do not throw Fatal signal 11 (SIGSEGV), but android 5.0 came later, I now the equipment is the android 6.0

**Comment by wangyangke** [comment]
No one encountered this problem?

**Comment by dukezhao** [comment]
I meet this problem too , how to fix it ?
when I open a local pic to enter the method  :nativeInit(datapath, language);
it crashed & log 
Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 26354 (Thread-21941)

my device: huawei kiw_AL10，android 6.0.1
