### ISSUE TITLE
ndk lib

### ISSUE THREAD

**Issue by Reginer** [rmtheis/tess-two#221]
Can you upload all the ndk libraries?

I want to use it this way:

ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86'//,'armeabi' ,'x86_64', 'mips', 'mips64'
        }

**Comment by rmtheis** [comment]
If you want to build all the ABIs you can edit the `Application.mk` files as you've done above and build the project yourself using the instructions in `BUILDING.md`, or you can use version 7.0.0, which includes all ABIs: ```compile 'com.rmtheis:tess-two:7.0.0```

**Comment by Reginer** [comment]
That's OK .
