### ISSUE TITLE
about white file

### ISSUE THREAD

**Issue by candrwow** [rmtheis/tess-two#223]
hello,can this lib support whitelist?I just want to ocr a-zA-Z 0-9. but always contains some chinese

**Comment by candrwow** [comment]
others,my target files always has backgroudcolor and textcolor ,there are many colors ,so how to solve it ? thank u.

**Comment by candrwow** [comment]
others,my target files always has backgroudcolor and textcolor ,there are many colors ,so how to solve it ? thank u.

**Comment by rmtheis** [comment]
Regarding whitelist, yes, see https://github.com/rmtheis/android-ocr/issues/29

Regarding colors, I'm not sure, maybe you can pre-process the image. Try asking on the Tesseract forum.

**Comment by rajputneeru** [comment]
please anybody can tell me , how to scan digital meter reading using this code 

thanks
