### ISSUE TITLE
UnsatisfiedLinkError, libopencv_java3.so is 64-bit instead of 32-bit

### ISSUE THREAD

**Issue by jenia** [rmtheis/tess-two#226]
Summary:
I cannot load tessaract when the app is starting.
I get "UnsatisfiedLinkError, libopencv_java3.so is 64-bit instead of 32-bit".

In contrast, when I remove tesseract from the project, I can load the app with opencv and use the functionality of opencv.

Can you please tell me how to load your project in the 64 bit version? Thanks

**Comment by anonym24** [comment]
https://github.com/rmtheis/tess-two/issues/197#issuecomment-335720132

**Comment by rmtheis** [comment]
This sounds to me like you need to use either the 32-bit version of both tess-two and OpenCV, or instead use the 64-bit version of both tess-two and OpenCV.

For this project, you can build versions for all ABIs using the instructions in BUILDING.md and setting the appropriate values for APP_ABI in Application.mk.

In any case, this is not a bug in this project.
