### ISSUE TITLE
TessBaseAPI - clear/end/stop doesn't really free all native memory

### ISSUE THREAD

**Issue by anonym24** [rmtheis/tess-two#227]
_Summary:_ TessBaseAPI - clear/end/stop doesn't really free up all native memory

```
TessBaseAPI.clear()
TessBaseAPI.stop();
TessBaseAPI.end();
```

_Steps to reproduce the issue:_

before initializing TessBaseAPI I usallly have ~10 mb native memory usage:

![befor init](https://user-images.githubusercontent.com/8851301/31427505-3108b8d8-ae70-11e7-87b2-235dc9872a4b.png)

When I start initializing my 8 instances of TessBaseAPI (cause TessBaseAPI works with multi-threading ok) with my button (onClick listener)

```
for (int i = 0; i < mTessArray.length; i++) {
    mTessArray[i] = new TessBaseAPI();
    mTessArrayij].init(mTessDataPath, mLanguageTess);
}
```

it will allocate + ~90 mb native memory:

![tess is init](https://user-images.githubusercontent.com/8851301/31427623-9735676e-ae70-11e7-93c5-b8ae8b0da09d.png)

so now it's around ~100 mb == (~10 + ~90)

but when I releasing all tess instances (I call all clear/stop/end methods for every instance)

```
if (mTessArray != null) {
   for (int i = 0; i < mTessArray.length; i++) {
            mTessArray[i].clear();
            mTessArray[i].stop();
            mTessArray[i].end();
            mTessArray[i] = null;
    }
    mTessArray = null;
}
```

it doesn't go back to ~10 mb (as was before initialization tess instances):

![tess is release](https://user-images.githubusercontent.com/8851301/31427947-b925b670-ae71-11e7-889a-165421d232d0.png)

did free up only ~20 mb

of course the problem is not about many instances, the same behavior would be also only for one instance, I just tested with what I had in my projects (many instances)

so the problem is about freeing up all used memory by tess

_Tess-two version:_
8.0.0

_Android version:_
6.0.1

_Phone/device model:_
Redmi 4 Prime/Pro

_Phone/device architecture:_
arm64-v8a (but I use armeabi-v7a so lib files - `ndk { abiFilters 'armeabi-v7a' }`

**Comment by rmtheis** [comment]
Nice catch. Interesting. Did you try a test where you force garbage collection such as by calling `System.gc()` afterwards?

What does the profile look like for calling that sequence of operations repeatedly with a single instance, like doing init->clear->stop->end repeatedly?

**Comment by anonym24** [comment]
Tried with one instance in new project:

```
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_tesseract_test);

        mTessDataPath = getFilesDir() + "/tesseract/";
        tessCheckFile(new File(mTessDataPath + "tessdata/"));

        // ~3 mb
        mHandler.postDelayed(new Runnable() {
            @Override
            public void run() {
                mTessArray = new TessBaseAPI();
                mTessArray.init(mTessDataPath, mLanguageTess);
                // ~12 mb

                mTessArray.clear();
                mTessArray.stop();
                mTessArray.end();
                mTessArray = null;
                System.gc();
                // ~10 mb (doesn't go back to ~3 mb)

                mHandler.postDelayed(this, 5000);
            }
        }, 5000);
    }
```

Same issue, before first Tesseract init I have about ~3 mb native memory used

After Tesseract init it allocates about ~12 mb native 
After releasing it's ~10 mb (not ~3 mb)

And after every 5 seconds 12, 10... 12, 10.... 12, 10 (at least it does not increase more than 12 mb)

**Comment by rmtheis** [comment]
> at least it does not increase more than 12 mb

Yes, that's a positive sign. If there were some kind of memory leak I would expect the memory usage to continue to increase for this case as the test continues to run.

Do you know if the behavior you found of not immediately listing native memory as deallocated differs from that of other projects that run native code?

**Comment by rmtheis** [comment]
Thanks for taking a look at this and running the tests. There may be motivation for doing more testing here, but as this stands, I'm not convinced that this behavior reflects an actual problem in the code. Please open a new issue if you find out new information -- I'd love to see it.
