### ISSUE TITLE
Text is not getting properly 

### ISSUE THREAD

**Issue by mavyasoni786** [rmtheis/tess-two#232]
Summary:
Could you please check my attached screenshot. I want to get a text from image using Tesseract library. Some text is not getting properly.

![device-2017-12-19-180200](https://user-images.githubusercontent.com/26457100/34157319-1d75e608-e4e7-11e7-95eb-edaee5bf786a.png)

**Comment by rmtheis** [comment]
Hmm, yes, this seems to be a side effect of the uneven text coloring used for the first phrase. You could pre-process the text using Leptonica if you want to adjust for this type of text. Working as intended.
