### ISSUE TITLE
run nativeInitOem() ;return false;why?

### ISSUE THREAD

**Issue by zj-captain** [rmtheis/tess-two#234]
Summary:
Simple APK is normal on other phone;i want to know why that;
run nativeInitOem();return false;why?

Steps to reproduce the issue:

1. 
2. 
3.

Expected result:

Actual result:

Tess-two version:

Android version:

Phone/device model:

Phone/device architecture (armeabi, armeabi-v7a, x86, mips, arm64-v8a, x86_64, mips64):

Link to training data used:

Link to image used as input:

**Comment by rmtheis** [comment]
Hmm, I'm not sure, it depends on the details. Could be something like the disk being full on one phone, or another issue relating to the training data installation.
