### ISSUE TITLE
How to add OPTITypewriter-Special font

### ISSUE THREAD

**Issue by mbsysde99** [rmtheis/tess-two#242]
Summary:
Hi Sir, how to add  [OPTITypewriter-Special font](https://www.ffonts.net/OPTITypewriter-Special.font) to training data? 

Thanks.
Anto

Steps to reproduce the issue:

1. 
2. 
3.

Expected result:

Actual result:

Tess-two version:
'com.rmtheis:tess-two:9.0.0

Android version:
AndroidStudio 3.1.1

Phone/device model:
Android PAX A920

Phone/device architecture (armeabi, armeabi-v7a, x86, mips, arm64-v8a, x86_64, mips64):
armeabi, armeabi-v7a, arm64-v8a

Link to training data used:

Link to image used as input:

**Comment by rmtheis** [comment]
See [Training Tesseract 3.03–3.05](https://github.com/tesseract-ocr/tesseract/wiki/Training-Tesseract-3.03%E2%80%933.05).
