### ISSUE TITLE
Skip tesseract's default image preprocessing (Otsu)

### ISSUE THREAD

**Issue by SivaramSS** [rmtheis/tess-two#243]
Summary:
I'm preprcessing the image using Brad Larsen AdaptiveThresholding. I want to stop the tesseract's default processing (Otsu thresholding). Is there any way to achieve that?

Tess-two version:
9.0

Android version:
8.1.1

Phone/device model:
Pixel XL

**Comment by rmtheis** [comment]
See https://stackoverflow.com/q/33239097/667810, which says that passing in an already-binarized image will bypass Tesseract's default processing.

If that doesn't work you can modify the C++ code in this project and build locally.

**Comment by SivaramSS** [comment]
Yes, but it says Android doesn't support 1bit bitmaps 
https://stackoverflow.com/questions/9377786/android-converting-a-bitmap-to-a-monochrome-bitmap-1-bit-per-pixel/15519513#comment11849170_9377943
