### ISSUE TITLE
compile binary only

### ISSUE THREAD

**Issue by TonyStark** [rmtheis/tess-two#244]
How to compile only android binary, so i can run tesseract from android terminal??
i compile library from `tess-two` folder using `ndk-build` command
but i could not find binary file

**Comment by rmtheis** [comment]
I'm not sure what you mean by the "Android terminal." But if you want the *.so binaries, for example libtess.so, you can get them directly from the [AAR](https://bintray.com/rmtheis/maven/tess-two/9.0.0#files/com%2Frmtheis%2Ftess-two%2F9.0.0) by unzipping it. Or see BUILDING.md.

**Comment by TonyStark** [comment]
![android-terminal-emulator-0](https://user-images.githubusercontent.com/5529450/40883587-70885bec-66f0-11e8-8f5c-588e51b15772.jpg)

Android terminal means command line (cli)
i want executable binary so i can run it from command line
i already build .so files, but could not find executable binary

**Comment by rmtheis** [comment]
This project doesn't provide that.

**Comment by avielas** [comment]
Hi
Can you give us a link?

**Comment by TonyStark** [comment]
Download termux app
Then open it and type `pkg install tesseract`
