### ISSUE TITLE
OCR number

### ISSUE THREAD

**Issue by polaris0227** [rmtheis/tess-two#245]
Summary:
I need to get numbers from image which contains only numbers.
Problem is that sometimes I got letters instead of numbers.
Please advice if anyone has solution.
Thanks.

Steps to reproduce the issue:

1. For instance, "51" on image, expected result is "51", but sometimes result is "SI". I know image only contains numbers only, but no way to force to get numbers.

Expected result:
"51"

Actual result:
"Sl"

Tess-two version:
8.0.0

Android version:
6.0

Phone/device model:
Hwawei

Phone/device architecture (armeabi, armeabi-v7a, x86, mips, arm64-v8a, x86_64, mips64):

Link to training data used:
eng.traineddata

Link to image used as input:
https://drive.google.com/open?id=17GNvsR2DlGf2yl9zZuppmfM8dxt81ymE

**Comment by rmtheis** [comment]
You can restrict the output to show only numbers by using a whitelist. See https://stackoverflow.com/q/38650899/667810

**Comment by polaris0227** [comment]
Thanks for your reply.
I have a question about whitelist.
Isn't it just for filtering?
I mean that if it detects "51" as "Sl", then it doesn't show any result.
if it detects "51" as "5l", then show "5" only...
I'm not sure if I say correctly.

**Comment by rmtheis** [comment]
No, the whitelist isn't just a post-OCR filter. With the whitelist, you'd see "51" where you would otherwise have seen "Sl".

**Comment by polaris0227** [comment]
Thank you very much for your help. 😊
