### ISSUE TITLE
error in Android 7.0

### ISSUE THREAD

**Issue by jamlu614** [rmtheis/tess-two#248]
Summary:
 error in Android 7.0 Could not initialize Tesseract API with language=""

Steps to reproduce the issue:

1. 
2. 
3.

Expected result:

Actual result:

Tess-two version:

Android version:7.0

Phone/device model:xiaomi 5

Phone/device architecture (armeabi, armeabi-v7a, x86, mips, arm64-v8a, x86_64, mips64):

Link to training data used:

Link to image used as input:

**Comment by rmtheis** [comment]
You didn't leave enough information to say for sure, but this error message is likely to result from a problem with your training data. See https://stackoverflow.com/a/50352472/667810.
