### ISSUE TITLE
Arabic trained-data produce 20% accuracy 

### ISSUE THREAD

**Issue by ibrahimAlii** [rmtheis/tess-two#250]
Summary:

When I use english data It's worked very well, but when I use arabic it's required to copy all `cube` data and also produced in bad quality.

Steps to reproduce the issue:

1. Input any arabic digits/words.
2. Get the `Utf8Text()`

Expected result:
I should get correct data.

Actual result:
I got wired result.

Tess-two version:
8.0.0

Android version:
28

Phone/device model:
Pixel

Link to training data used:
https://github.com/tesseract-ocr/tessdata/blob/3.04.00/ara.traineddata

Link to image used as input:

http://3.bp.blogspot.com/-CZRdjlj2ybU/TkAbU6C4RWI/AAAAAAAAAAw/n4Hej0ct3rw/s1600/ind.jpg

**Comment by rmtheis** [comment]
Thanks for the bug report. It's not entirely clear to me what the problem is because you just said you get a "weird result." Maybe try different page segmentation modes and try using different portions of the input image.

Most likely your issue is not a bug and this is working as intended.

**Comment by ibrahimAlii** [comment]
@rmtheis  Please check below image

![screenshot_1537628905](https://user-images.githubusercontent.com/21141301/45918631-304e4400-be8a-11e8-9c16-0c45bf57314c.png)

The result is should be like picture I got some arabic character instead of digits, also there is digits like one and three i got nine instead of one and "ها" instead of three and "هلا" instead of six.
