### ISSUE TITLE
java.lang.NoSuchFieldError: no "I" field "mNativeData" in class "Lcom/googlecode/tesseract/android/TessBaseAPI;" or its superclasses

### ISSUE THREAD

**Issue by NirmalPrajapat** [rmtheis/tess-two#251]
Getting **java.lang.NoSuchFieldError: no "I" field "mNativeData" in class "Lcom/googlecode/tesseract/android/TessBaseAPI;" or its superclasses** while running the app on all device except Samsung galaxy S7. It working well on this device but not on others.

I am using 
**compile group: 'com.rmtheis', name: 'tess-two', version: '9.0.0'**
 in my studio project.

**Comment by rmtheis** [comment]
Possibly related: #82 and #166.  Please add steps to reproduce the issue, and let me know if running the test cases works for you.

**Comment by NirmalPrajapat** [comment]
Process: com.TessProj.tessocr, PID: 9806
                  java.lang.NoSuchFieldError: no field with name='mNativeData' signature='I' in class Lcom/googlecode/tesseract/android/TessBaseAPI;
                      at com.googlecode.tesseract.android.TessBaseAPI.nativeClassInit(Native Method)
                      at com.googlecode.tesseract.android.TessBaseAPI.<clinit>(TessBaseAPI.java:54)
                      at com.fabercomputing.tessocr.TessOCR.<init>(TessOCR.java:20)

in **build.gradle**
defaultConfig {
        applicationId "com.fabercomputing.tessocr"
        minSdkVersion 16
        targetSdkVersion 17
        consumerProguardFiles "proguard-rules.pro"
    }
