### ISSUE TITLE
Tess4 initialize crash

### ISSUE THREAD

**Issue by irann93** [rmtheis/tess-two#255]
Summary:
Tesseract crash when I use tessdata 4.0 from 
> https://github.com/tesseract-ocr/tessdata
 
but it works well with older tessdata (version 3.05)

Steps to reproduce the issue:

> private static final String DATA_PATH = Environment.getExternalStorageDirectory().toString() + "/Tess";
> TessBaseAPI api = new TessBaseAPI();
> api.init(DATA_PATH, "eng");
> String tessVersion = api.getVersion();
> api.setPageSegMode(TessBaseAPI.PageSegMode.PSM_SINGLE_BLOCK);

Expected result:
Tesseract should initialize properly

Actual result:
Tesseract crash at line
> api.init(DATA_PATH, "eng");

Tess-two version:
Tesseract 4.0alpha  from github using jni

Android version:
7.0

Phone/device model:
Galaxy Tab A(2016) with S pen

Phone/device architecture (armeabi, armeabi-v7a, x86, mips, arm64-v8a, x86_64, mips64):
not sure

Link to training data used:
> https://github.com/tesseract-ocr/tessdata

Link to image used as input:
no output

**Comment by rmtheis** [comment]
This is working as intended. Tesseract 4 isn't supported -- see #196.
