### ISSUE TITLE
Could not initialize Tesseract API with language=ces!

### ISSUE THREAD

**Issue by davidbulant** [rmtheis/tess-two#258]
Summary:

TessBaseAPI tessBaseApi = new TessBaseAPI();
tessBaseApi.init("/storage/emulated/0/MyTesseractData/tessdata", "ces");

after init is called => E/Tesseract(native): Could not initialize Tesseract API with language=ces!

Tried eng.traineddata, slk.traineddata (3.0.4 version) for sanity check. They were initialized without problem.

Tess-two version:
9.0.0, 8.0.0, 7.0.0, 6.3.0, 6.2.0, latest version build from source
Did not try older versions.

Android version:
6.0.1

Phone/device model:
Moto G (3rd generation)

Phone/device architecture (armeabi, armeabi-v7a, x86, mips, arm64-v8a, x86_64, mips64):

Link to training data used:
https://github.com/tesseract-ocr/tessdata/blob/3.04.00/ces.traineddata

**Comment by rmtheis** [comment]
[Try](https://github.com/rmtheis/tess-two/blob/ac415295cdbc202e258cedcf667268e5ae0e56f5/tess-two/src/com/googlecode/tesseract/android/TessBaseAPI.java#L271) tessBaseApi.init("/storage/emulated/0/MyTesseractData/", "ces");

**Comment by rmtheis** [comment]
Thanks for the report. Closing this issue because it doesn't look like a problem with this project.
