### ISSUE TITLE
read Jpeg and PNG produce wrong alpha in 32bpp pix

### ISSUE THREAD

**Issue by alexcohn** [rmtheis/tess-two#264]
The tests **ReadFileTest.testReadFile_jpg()** and **ReadFileTest.testReadFile_png()** fail for me, with an arm64 device.

See https://github.com/DanBloomberg/leptonica/issues/442. An easy fix inside leptronica can be pulled, but maybe I am missing something and these tests pass for you?

**Comment by alexcohn** [comment]
probably this happens for me because I used [a different version](https://github.com/renard314/tess-two/commit/3de4bea67d6270bbbb77af49ddb20525da52f410#diff-7a6e9b90228e58eb878bd24fceaa51ee) of **readfile.cpp**.

**Comment by alexcohn** [comment]
The problem has been [discussed before](https://github.com/rmtheis/tess-two/issues/87). The current version produces Pix with **bpp8** from **ReadFIle.readBitmap()**, and loosing alpha information is only a small issue; RGB colors get distorted, too (OK, for grayscale bitmaps, the result may be OK).

**Comment by rmtheis** [comment]
Thank you for looking into and fixing this issue. This one was a longstanding issue.

**Comment by alexcohn** [comment]
I have fixed this and similar WriteFile tests in [my fork](https://github.com/alexcohn/Tesseract4Android), which uses Tesseract 4.0. Should I create a special Pull Request for these changes, or maybe it would be wise to move the whole project to Tesseract 4.0 ?
