### ISSUE TITLE
Crash on Android L

### ISSUE THREAD

**Issue by emartynov** [rmtheis/tess-two#268]
Summary:
We see crash on the L phones:

```
Fatal Exception: java.lang.UnsatisfiedLinkError
dlopen failed: could not load library "libjpgt.so" needed by "liba.so"; caused by library "libjpgt.so" not found
java.lang.Runtime.loadLibrary (Runtime.java:371)
java.lang.System.loadLibrary (System.java:989)
com.googlecode.tesseract.android.TessBaseAPI.<clinit> (TessBaseAPI.java:51)
```

Steps to reproduce the issue:

No steps - crashing in the wild

Expected result:
No crash

Tess-two version:
com.rmtheis:tess-two:9.0.0

Android version:
5.1.1 and 5.0.1

Phone/device model:
Samsung J3 and S4, HTC One (M8)

Phone/device architecture (armeabi, armeabi-v7a, x86, mips, arm64-v8a, x86_64, mips64):
32 bit

**Comment by emartynov** [comment]
I hear many times there are a lot of possible issues with loading native libraries. Do you consider to use https://github.com/KeepSafe/ReLinker for loading native libs?

**Comment by rmtheis** [comment]
Possibly related: #150, #127.

Thank you for the issue report. I'm not planning to continue maintenance on this repo so I'm going to close this issue.
