### ISSUE TITLE
Has anyone tried the multi-language support featured in tesseract 3.02?

### ISSUE THREAD

**Issue by iori57** [rmtheis/tess-two#28]
I tried the new multi-language feature in tesseract 3.02 but it doesn't seem to work.

For example, the image contains english and japanese words so during initialization I put in english + japanese combo:
_tesseract = new TessBaseAPI();
_tesseract.init(tesseractDatapath, "eng+jpn");
_tesseract.setImage(_imageToProcess);

The ocr result seems to be the same whether i use "eng" or "eng+jpn", english seems to dominate and the japanese words become random symbols. If i just use "jpn" the japanese words do get ocr'ed nicely into text but obviously the english words doesn't get ocr'ed well.

At this point I'm not sure if multi-language a false advertising on Google's side, or is the android version tess-two doesn't support multi-language?

Thanks in advance!
Bruce

**Comment by 786lokesh** [comment]
Train languages into one by merging the files can be another approach. Let the user select the languages which they would like to OCR and then merge em together to get the desired result. I also faced the same problem, working on it.
