### ISSUE TITLE
ndk-build fail, .o.d file is generated after compile instead of .o file

### ISSUE THREAD

**Issue by rsteng2** [rmtheis/tess-two#41]
I am using windows 8.1 64  bit and android ndk r9c. I am using Git shell to ndk-build tess-two. Some error occur like below:
![picture1](https://f.cloud.github.com/assets/6178906/2179631/a8f237fc-96c3-11e3-9a88-86e9a0f7d4b4.png)
The object directory show .o.d file.
![picture2](https://f.cloud.github.com/assets/6178906/2179633/ba5e1f56-96c3-11e3-898a-d25af2c8fcec.png)

Any reason to this problem. Thanks. I am still a beginner in this, so there might be some  silly mistake i have done. Truly appreciate for any advice.

**Comment by elecstudent** [comment]
Hi there, 
I am trying to run same app, but I get following error:
"
C:\Users\Mcodes\tess-two-master\tess-two>ndk-build
[armeabi] Compile thumb  : jpgt <= jaricom.c
error: error opening './obj/local/armeabi/objs/jpgt/jaricom.o.d': Error opening
      output file './obj/local/armeabi/objs/jpgt/jaricom.o.d': No such file or
      directory
1 error generated.
make.exe: *** [obj/local/armeabi/objs/jpgt/jaricom.o] Error 1
"

**Comment by elecstudent** [comment]
Can anyone help me to fix above error? Many thanks
