### ISSUE TITLE
user_patterns_suffix

### ISSUE THREAD

**Issue by Tindaro85** [rmtheis/tess-two#45]
Hi, 
I would like to use the Tesseract feature described here in "CONFIG FILES AND AUGMENTING WITH USER DATA" : http://tesseract-ocr.googlecode.com/svn-history/r719/trunk/doc/tesseract.1.html

I need to specify a regex to match the recognition of a particular set of words.
In the doc they said that this can be done setting the variable "user_patterns_suffix" that takes as value the name of a file "user-patterns" where I need to put the regex.
I created a config file and put it in configs/ dir, then I loaded it with the ReadConfigFile() method of tess-two API.
This doesn't seem to work as expected.
I'm sure that the config file is correctly loaded because if I try to set in the file the "tessedit_char_whitelist" property, this works as expected.
So I think that the problem is in the "user_patterns_suffix".

Any idea? 
Is there any alternative tess-two API method to limit the recognition of Tesseract to a set of words given a regex?

Thanks in advance for your help

**Comment by rmtheis** [comment]
Combining this issue with issue #64.
