### ISSUE TITLE
Add support for PDF output with searchable text?

### ISSUE THREAD

**Issue by iori57** [rmtheis/tess-two#46]
In Tesseract 3.03 release notes it mentions 'Added support for PDF output with searchable text.'

Wonder if tess-two can add support to it?

Seems like someone tried in stackoverflow but couldn't get it to work with tess-two:
http://stackoverflow.com/questions/21719708/tesseract-v3-03-render-pdf-with-searchable-text-example

Thanks in advance!

**Comment by rmtheis** [comment]
I've merged in code for doing this from the "doo" branch. A big thanks to doo GmbH for that.
