### ISSUE TITLE
Support for Parameterized Init

### ISSUE THREAD

**Issue by gene-chan** [rmtheis/tess-two#64]
We need a way to pass init-only variables when calling init, such as load_system_dawg.

**Comment by rmtheis** [comment]
https://github.com/tesseract-ocr/tesseract/wiki/ControlParams#init-only

**Comment by 9tontruck** [comment]
What is the conclusion of how to use user_patterns_suffix? There are only referenced links without any comments so I am just jumping around the same links

**Comment by rmtheis** [comment]
@9tontruck user_patterns_suffix is not currently supported. Support for it is a proposed enhancement.

**Comment by Maragues** [comment]
Hi, so there's currently no way to set * load_system_dawg* to false? I also don't see a way to get the raw result before it's processed by dictionary related code.

I'm working on recognizing random alphanumeric strings and disambiguating with a dictionary is of course returning wrong results

**Comment by rmtheis** [comment]
Closing old issues that haven't been acted on.
