### ISSUE TITLE
Running Tess-two with Android Studio

### ISSUE THREAD

**Issue by danielevitali** [rmtheis/tess-two#70]
I am trying to using the library with Android Studio.
I built the library as stated, then I followed this article in order to import it in Android Studio using Gradle.
https://coderwall.com/p/eurvaq/tesseract-with-andoird-and-gradle

However, I get this error when try to get the text from bitmap using getUTF8Text():

TessBaseAPI baseApi = new TessBaseAPI();
baseApi.setDebug(BuildConfig.DEBUG);
baseApi.init(getFilesDir().getAbsolutePath() + File.separator, "eng");
baseApi.setImage(bitmap);
String recognizedText = baseApi.getUTF8Text().trim();

Could not initialize Tesseract API with language=eng!
A/libc﹕ Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 19824 (p.android.debug)

I thought it was caused by the traineddata asset, but as my app starts the file is copied from assets to tessdata folder inside the app directory.

I found strange that the build.gradle file from the article has declared this line:
jniLibs.srcDirs = ['libs']
when the article says to delete the libs folder.

Can anyone help me with this please?

**Comment by carconper** [comment]
Hi Daniele

Could you please share with us the solution or the procedure you followed
to resolve the issue?

Thank you

Best regards

Carlos

On Monday, January 5, 2015, Daniele <notifications@github.com> wrote:

> Closed #70 <https://github.com/rmtheis/tess-two/issues/70>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rmtheis/tess-two/issues/70#event-214025798>.
>


-- 
Carlos Conde Pereda

**Comment by danielevitali** [comment]
Hi Carlos.
There was a problem with the algorithm for coping the traineddata file.
When the app was starting, an exception was raised and caught but not logged.
So nothing related to Tess-two or Android Studio or Gradle.

Regards.
Daniele

**Comment by carconper** [comment]
Thank you for the clarification Daniele :)

On Tue, Jan 6, 2015 at 12:54 AM, Daniele <notifications@github.com> wrote:

> Hi Carlos.
> There was a problem with the algorithm for coping the traineddata file.
> When the app was starting, an exception was raised and caught but not
> logged.
> So nothing related to Tess-two or Android Studio or Gradle.
>
> Regards.
> Daniele
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rmtheis/tess-two/issues/70#issuecomment-68840586>.
>



-- 
Carlos Conde Pereda

**Comment by hagerrady13** [comment]
Hello Daniel, i am still facing a problem after building the libraries. I followed the mentioed steps and wrote this code to test it:
       Bitmap bitmap;
        bitmap = BitmapFactory.decodeResource(null, R.drawable.eng);
        TessBaseAPI baseApi = new TessBaseAPI();
        baseApi.setDebug(BuildConfig.DEBUG);
        baseApi.init(getFilesDir().getAbsolutePath() + File.separator, "eng");
        baseApi.setImage(bitmap);
        String recognizedText = baseApi.getUTF8Text().trim();
        Log.i("The text", recognizedText);
and I got an error when building that the package does not exist and TessBaseAPI does not exist, Nay help? I have been trying to build the libarary since three days and it is not working yet.
