### ISSUE TITLE
ndk-build: command not found

### ISSUE THREAD

**Issue by DenkoSx** [rmtheis/tess-two#72]
I am relatively new to android development and I have a problem building the project at the step 'ndk-build'. 
Error - "Command not found"
I posted a screenshot too. 
Edit: Im using a 64bit Kubuntu 14.10
![snapshot1](https://cloud.githubusercontent.com/assets/10849015/6059550/dacc0e44-ad3b-11e4-8f5d-863f2e7c183b.png)

**Comment by rmtheis** [comment]
ndk-build is installed with the Android NDK.
