### ISSUE TITLE
undefined reference to android_getCpuFeatures link error when building armeabi-v7a common library with ndk r10d

### ISSUE THREAD

**Issue by semicolo** [rmtheis/tess-two#73]
When building tess-two with the r10d version of the NDK on windows 8, linking of the common shared library errors with "undefined reference to android_getCpuFeatures".

Adding 
LOCAL_STATIC_LIBRARIES := cpufeatures
and 
$(call import-module,android/cpufeatures)

to the jni/common/Android.mk file fixed it.

Here's the content of this file now on my computer:

LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_SRC_FILES := time_log.cpp

LOCAL_CFLAGS := -Wall \
                -DHAVE_MALLOC_H \
                -DHAVE_PTHREAD \
                -finline-functions \
                -frename-registers \
                -ffast-math \
                -s \
                -fomit-frame-pointer

ifeq ($(LOG_TIME),true)
  LOCAL_CFLAGS += -DLOG_TIME
endif

LOCAL_STATIC_LIBRARIES := cpufeatures

LOCAL_MODULE := common

include $(BUILD_STATIC_LIBRARY)

$(call import-module,android/cpufeatures)

**Comment by rmtheis** [comment]
I don't see the "undefined reference" error on my Windows box. Any idea if there's some setting that triggers it?

You see this for eyes-two, right?

I suppose it wouldn't hurt to make the change to Android.mk anyway, despite my not seeing the error.

**Comment by semicolo** [comment]
It looks like I messed up something somewhere, I removed all the files and did a fresh build from a fresh pull and it worked. Sorry about that.
