### ISSUE TITLE
Cancel a progressing OCR computation?

### ISSUE THREAD

**Issue by gre** [rmtheis/tess-two#74]
In an equivalent tesseract library for iOS : https://github.com/gali8/Tesseract-OCR-iOS there is possibility to implement a function `shouldCancelImageRecognitionForTesseract` which tell if the image recognition should be cancelled.

This feature would be awesome, do you think it is easily possible to have it or does it imply complex consistency/concurrency/memory-leak issues?

**Comment by rmtheis** [comment]
Try out the recently-added stop() method and let me know how that works for you. I really haven't thoroughly tested it yet at this point, so you may run into issues like those you've mentioned.
