### ISSUE TITLE
issue: ndk-build  command not found 

### ISSUE THREAD

**Issue by Lansing111** [rmtheis/tess-two#76]
I am relatively new to android development and I have a problem building the project at the step 'ndk-build'. 
Error - "Command not found"
I posted a screenshot too. 
Edit: Im using a 64bit mac OS

![screen shot 2558-03-14 at 14 20 20](https://cloud.githubusercontent.com/assets/10734152/6653191/76acabbc-ca55-11e4-8895-d4744f55d839.png)

**Comment by rmtheis** [comment]
You have to add the NDK directory to your PATH. Google "mac add to path".
