### ISSUE TITLE
Crash in TessBaseAPI.getUTF8Text()

### ISSUE THREAD

**Issue by Linuxhippy** [rmtheis/tess-two#77]
Hello,

I try to use Tess-Two on a Galaxy Note4 running Android-4.4.4. All the initialization steps succeed, however as soon as getUTF8Text() is called the application terminates.

At initialization time, the following steps are performed and tessSuccess is true afterwards:
     baseApi = new TessBaseAPI();
     baseApi.setDebug(true);
     boolean tessSuccess = baseApi.init(appDir.getPath(), "de");

Inside the onPictureTaken() method of the PictureCallback, everything works until getUTF8Text() is invoked:
     BitmapFactory.Options op = new BitmapFactory.Options();
     op.inPreferredConfig = Bitmyap.Config.ARGB_8888;
     Bitmap bitMap = BitmapFactory.decodeByteArray(bytes, 0, bytes.length, op);

     baseApi.setImage(bitMap);
     String text = baseApi.getUTF8Text(); //Crash

The bitmap Object seems to be valid (1920x1080 ARGB_8888), I tried to downsample it which didn't help unfourtunately. I used tess-two git from 20150427.

The crash seems to be caused by dereferencing a nullpointer: 
04-27 17:34:14.980  10609-10609/com.example.cam A/libc﹕ Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 10609 (com.example.cam)

Thanks, Clemens

**Comment by rmtheis** [comment]
Are you using the v3.02 traineddata for "deu"? And can you post a link to the bitmap?

**Comment by Linuxhippy** [comment]
Yes, I used the traineddata v3.02 for "deu", available here: https://code.google.com/p/tesseract-ocr/downloads/detail?name=tesseract-ocr-3.02.deu.tar.gz&can=2&q=

The bitmap was not saved, but instead provided directly by the camera:

                        public void onPictureTaken(byte[] bytes, Camera camera) {
                            BitmapFactory.Options op = new BitmapFactory.Options();
                            op.inPreferredConfig = Bitmap.Config.ARGB_8888;
                            Bitmap bitMap = BitmapFactory.decodeByteArray(bytes, 0, bytes.length, op);

                            camTest.baseApi.setImage(bitMap);
                            String text = camTest.baseApi.getUTF8Text();
                            Toast.makeText(camTest, text, Toast.LENGTH_LONG).show();
                        }

Could the issue be that I called BaseApi.init with language "de" instead of "deu"? 
However, init returned true so I guess this isn't the issue,,,

**Comment by Linuxhippy** [comment]
> Could the issue be that I called BaseApi.init with language "de" instead of "deu"? 

This was causing the crash, changing "de" to "deu" solved the problem, however I guess it just should not work instead of throwing a SIGSEV ;)
