### ISSUE TITLE
JNI GetMethodID called with pending exception 'java.lang.NoSuchFieldError'

### ISSUE THREAD

**Issue by ferrygun** [rmtheis/tess-two#80]
Hi,

I am getting this error message when running the app. I am not sure what's going on here. Can you please help me with this?

JNI DETECTED ERROR IN APPLICATION: JNI GetMethodID called with pending exception 'java.lang.NoSuchFieldError' thrown in void com.googlecode.tesseract.android.TessBaseAPI.nativeClassInit():-2

Thank you.

**Comment by rmtheis** [comment]
You closed this issue--are you still getting the error? What version of Android are you running on? And what version of the NDK did you use to build?

**Comment by ferrygun** [comment]
Hi Robert,

Yes I managed to solve the issue. The issue was with the misplacement of the Java codes.Nothing wrong with NDK or other things. Thanks for your response.

**Comment by rmtheis** [comment]
Glad you got it fixed. If you write some more detail about what you had wrong, that might be helpful to others.
