### ISSUE TITLE
OCR (tesseract) crashes in blackberry 10.2 ported app

### ISSUE THREAD

**Issue by zulfiqarchandio** [rmtheis/tess-two#83]
I have implemented this ocr library in my app and ported to blackberry. Its working fine in android and blackberry 10.3, But crashes in blackberry 10.2.

I am getting this log:
08-31 09:45:01.507: E/AndroidRuntime(12181540): FATAL EXCEPTION: main
08-31 09:45:01.507: E/AndroidRuntime(12181540): java.lang.ExceptionInInitializerError
08-31 09:45:01.507: E/AndroidRuntime(12181540):     at com.app.ocr.CaptureActivity.initOcrEngine(CaptureActivity.java:860)
08-31 09:45:01.507: E/AndroidRuntime(12181540):     at com.app.ocr.CaptureActivity.onResume(CaptureActivity.java:484)
08-31 09:45:01.507: E/AndroidRuntime(12181540):     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1185)
08-31 09:45:01.507: E/AndroidRuntime(12181540):     at android.app.Activity.performResume(Activity.java:5225)
08-31 09:45:01.507: E/AndroidRuntime(12181540):     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2732)
08-31 09:45:01.507: E/AndroidRuntime(12181540):     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2771)
08-31 09:45:01.507: E/AndroidRuntime(12181540):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2235)
08-31 09:45:01.507: E/AndroidRuntime(12181540):     at android.app.ActivityThread.access$600(ActivityThread.java:141)
08-31 09:45:01.507: E/AndroidRuntime(12181540):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
08-31 09:45:01.507: E/AndroidRuntime(12181540):     at android.os.Handler.dispatchMessage(Handler.java:99)
08-31 09:45:01.507: E/AndroidRuntime(12181540):     at android.os.Looper.loop(Looper.java:137)
08-31 09:45:01.507: E/AndroidRuntime(12181540):     at android.app.ActivityThread.main(ActivityThread.java:5049)
08-31 09:45:01.507: E/AndroidRuntime(12181540):     at java.lang.reflect.Method.invokeNative(Native Method)
08-31 09:45:01.507: E/AndroidRuntime(12181540):     at java.lang.reflect.Method.invoke(Method.java:511)
08-31 09:45:01.507: E/AndroidRuntime(12181540):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:840)
08-31 09:45:01.507: E/AndroidRuntime(12181540):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:607)
08-31 09:45:01.507: E/AndroidRuntime(12181540):     at dalvik.system.NativeStart.main(Native Method)
08-31 09:45:01.507: E/AndroidRuntime(12181540): Caused by: java.lang.UnsatisfiedLinkError: No suitable loading module found.
08-31 09:45:01.507: E/AndroidRuntime(12181540):     at java.lang.Runtime.loadLibrary(Runtime.java:371)
08-31 09:45:01.507: E/AndroidRuntime(12181540):     at java.lang.System.loadLibrary(System.java:540)
08-31 09:45:01.507: E/AndroidRuntime(12181540):     at com.googlecode.tesseract.android.TessBaseAPI.<clinit>(TessBaseAPI.java:44)
08-31 09:45:01.507: E/AndroidRuntime(12181540):     ... 17 more

Any help will be thankful.

**Comment by rmtheis** [comment]
Sounds like a Blackberry bug. It would be helpful if you said which version of the NDK you used to compile, and what kind of hardware you're running on.

**Comment by zulfiqarchandio** [comment]
I compiled on android-ndk-r9, And running on Blackberry Z30, Model
no:STA100-2, Software release: 10.2.0.224

Thanks

**Comment by rmtheis** [comment]
Have you tried building with a newer version of the NDK?

**Comment by zulfiqarchandio** [comment]
not tried. But I also tried sample app OCR-Test. facing same issue. let me
try newer NDK.

Thanks

**Comment by rmtheis** [comment]
Yeah, I'd suggest opening a bug with Blackberry, assuming the build with the newer NDK doesn't fix it. It could be just a bug that they fixed in Blackberry 10.3.

**Comment by zulfiqarchandio** [comment]
Yea,  I tried on ndk 10 but facing same issue. It must be blackberry bug.

Thanks for your help.
