### ISSUE TITLE
How can I use this library in Cordova Plugin.

### ISSUE THREAD

**Issue by Fibinacci** [rmtheis/tess-two#84]
I want to use this library when developing hybrid applications Cordova. I need to create a plug-in for it.
I appreciate people who have the knowledge of Cordova could tell me how to do it. When I tried to make ,the application can not access the com.googlecode.tesseract.android.

**Comment by rmtheis** [comment]
Take a look at the PhoneGap API documentation [1] and maybe post to StackOverflow if you have questions.

[1] http://docs.phonegap.com/en/2.2.0/guide_plugin-development_android_index.md.html#Developing%20a%20Plugin%20on%20Android
