### ISSUE TITLE
Problem of more line scan(example; paragraph)

### ISSUE THREAD

**Issue by Fibinacci** [rmtheis/tess-two#89]
I can get good results in one line. But when two or more lines, did not properly value what I did.
I tried a few kinds of methods in PageSegMode. But I could not fix it.

In the meantime, I'm using tesseract_only engine.(Because cube engine not support mine language). How can I improve the tesseract results. Are there steps that should be followed in this regard?

**Comment by rmtheis** [comment]
Try asking your question on StackOverflow or the tesseract-ocr mailing list. Be sure to include the image you're using and the Tesseract methods that you're calling.
