### ISSUE TITLE
Recognize Problem in 5.0.1 android

### ISSUE THREAD

**Issue by RanchhodRamani** [rmtheis/tess-two#90]
I have implement Tessract Library and recognize text using my different  devices. but it not work fine in all devices.    
Recognize from clear image that contain only one digit. but it give every time null data. i am capturing image from native android app camera.
Note: i have implement only Tessbase class only.
please help me out from the problem.

**Comment by rmtheis** [comment]
Try asking your question on the tesseract-ocr mailing list or on StackOverflow, and be sure to include details like a sample image and the settings/methods/code you're using.
