### ISSUE TITLE
setPageSegMode is work on 5.0.0 ?

### ISSUE THREAD

**Issue by Fibinacci** [rmtheis/tess-two#91]
I tried all kinds of pagesegmode. They all get the same results. How to understand the impact of this. Does it impact on the value from getutf8text()? Even in setPageSegMode(45) and then also it works without error. But same result. 

Then I updated to version 5.0.1.  This time, TessBaseAPI baseApi = new TessBaseAPI(); As the line does not continue program without receiving any error. It does not return the results back. In fact,the program does not exceed this command.

**Comment by rmtheis** [comment]
What happens when you run the unit tests?

**Comment by Fibinacci** [comment]
I do not understand what you mean by unit tests.

**Comment by rmtheis** [comment]
I mean running `runtests.sh`. The problem creating the TessBaseAPI object sounds like a problem with your code.

Setting the page segmentation mode doesn't guarantee that you'll get a different result. If you have questions about it try the tesseract-ocr mailing list.
