### ISSUE TITLE
Single Character recognition 

### ISSUE THREAD

**Issue by reachwasim** [rmtheis/tess-two#93]
Hello, i was trying to recognize Single char, but no help. 
Can you please advice me what should i look into?
I dont know if i have to look into the trained data? 
It would be a great help if you could look into this.

**Comment by rmtheis** [comment]
Look in `TessBaseAPI.java` for `PageSegMode` value `PSM_SINGLE_CHAR`:

    baseApi.setPageSegMode(PageSegMode.PSM_SINGLE_CHAR);
